"""Original page content for Hamilton Care Dental Centre site rebuild.

All body copy is written originally for this rebuild based on general dental
domain knowledge. Hero images are sourced from the practice's own assets
(downloaded into /assets/images/scraped/). Business identifiers (NAP, dentist
names, service names) are factual and reused as-is.
"""

# Map: page slug -> hero filename (in /assets/images/scraped/) OR fallback hero in /assets/images/
HERO_MAP = {
 # Core pages
 "about-us": "696866587ed8f107ea46c01d_IMG_7592.CR3_compressed.JPEG",
 "our-story": "696866587ed8f107ea46c01d_IMG_7592.CR3_compressed.JPEG",
 "services": "69823a60259f0beff7e0e59d_IMG_1932.JPG",
 "contact-us": "696869207a6acaa7ac1d368d_IMG_7577-Edited-min-2048x1365.jpg",
 "new-patients": "696869207a6acaa7ac1d368d_IMG_7577-Edited-min-2048x1365.jpg",
 "blog": "69dd357ddd5316a68625f91e_wisdom-teeth-removal-hamilton-care-dental-centre.jpg",
 "payment-plans": "6a04c1d25217f5426cd9cbe6_beautify_financing.webp",
 "canadian-care-dental-plan": "69544ac938513c9b12f2dded_Dentists-Denturistour-story-1024x1024.png",
 "referral-form": "69544ac938513c9b12f2dde5_Untitled-design-14-min-555x740.png",
 "thank-you": "69544ac938513c9b12f2dde5_Untitled-design-14-min-555x740.png",
 "privacy-policy": "69544ac938513c9b12f2dde4_Untitled-design-17-min-555x740.png",
 "style-guide": "69544ac938513c9b12f2dde5_Untitled-design-14-min-555x740.png",

 # Service detail pages
 "cosmetic-dentistry": "cos1.png",
 "dental-implants": "698237a0315ecee2c52c1f82_istockphoto-1811278606-612x612.jpg",
 "endodontics": "endodontics.jpg",
 "miscellaneous": "m1.png",
 "nitrous-sedation": "nitrous-sedation.jpg",
 "oral-surgery": "69575b656e3432c4987283e6_PICT0184.jpg",
 "preventative-dentistry": "prev1.jpg",
 "restorative-dentistry": "rest1.png",
 "suresmile-clear-aligners": "6982397522a67279467e28ff_Screenshot_2026-02-03_130614.jpg",
}

# Service pages: slug -> data
SERVICES = {
 "cosmetic-dentistry": {
 "name": "Cosmetic Dentistry",
 "short": "Smile makeovers that combine veneers, whitening, bonding, and aligners, shaped around your face and goals.",
 "intro": "Cosmetic dentistry improves the appearance of your teeth, gums, and overall smile. From a single chipped tooth to a full smile makeover, our team designs treatment plans that look natural and last.",
 "what_it_is": "Cosmetic dentistry includes any treatment that improves how your smile looks, porcelain veneers, professional whitening, composite bonding, gum recontouring, tooth-coloured crowns, and clear-aligner orthodontics. We focus on conservative options first and only recommend more involved treatments when they will give a meaningfully better result.",
  "sub_services": [
  "Porcelain Veneers",
  "Dental Crowns",
  "Crown Lengthening",
  "White Spot Treatment",
  "Composite Bonding",
  "Smile Makeovers",
 ],
 "good_for": [
 "Discoloured or stained teeth",
 "Chipped, cracked, or worn enamel",
 "Small gaps or crowding",
 "Gummy smiles or uneven gum lines",
 "Old metal fillings or crowns showing through",
 ],
 "process": [
 ("Smile consultation", "We listen to what you want to change about your smile and discuss realistic, durable options."),
 ("Smile design", "Using photos and digital previews, we plan the size, shape, shade, and proportions of each tooth so the final result fits your face."),
 ("Treatment", "Depending on the plan, this can include whitening, bonding, <a href='/services/cosmetic-dentistry/'>veneers</a>, crowns, or clear aligners."),
 ("Final reveal & care", "We refine your bite, polish everything, and review home-care tips so your new smile lasts."),
 ],
 "faqs": [
 ("How do I know which treatment is right for me?", "Book a smile consultation. We will examine your teeth, listen to your goals, and explain conservative options before any major work."),
 ("Are veneers permanent?", "Porcelain <a href='/services/cosmetic-dentistry/'>veneers</a> require minimal enamel removal and last 10â15 years on average. They are considered a long-term commitment."),
 ("Will cosmetic dentistry damage my teeth?", "When planned and placed properly, modern <a href='/services/cosmetic-dentistry/'>cosmetic dentistry</a> preserves natural tooth structure and often strengthens weakened teeth."),
 ("Does insurance cover cosmetic work?", "Most insurance plans cover restorative components but not purely cosmetic treatments. We offer flexible payment plans and <a href='/payment-plans/'>Beautifi financing</a>."),
 ],
 "deep_content": [
  ("How we plan a smile", "<p>Most cosmetic work goes sideways when the plan skips the boring part. Before we touch a tooth we take photos from a few angles, do a quick bite check, and either mock up the proposed shape directly on your teeth with composite or run a digital preview in our scanner. You get to see roughly what the final result will look like before any drilling happens. If the preview is not quite right, we adjust on the screen, not on the tooth. That single step prevents most of the regret stories you hear about veneers.</p><p>We usually whiten first, then plan any bonding, veneers, or crowns afterward so the new material matches the brighter shade. The order matters. Whitening after veneers will not change the porcelain colour and you will end up with a two-tone smile.</p>"),
  ("Bonding, veneers, or crowns, which is the right pick", "<p>For one chip or a small gap, composite bonding done freehand finishes in one visit and costs roughly $250 to $450 per tooth. It can be polished and adjusted any time. The trade-off is bonding stains over five to ten years and chips more easily than porcelain.</p><p>For shape, length, or shade changes across the front six or eight teeth, porcelain veneers are the durable answer. They run roughly $1,200 to $1,800 per tooth and last ten to fifteen years on average. We remove very little enamel, usually less than a millimetre, and many cases are no-prep. A full crown is reserved for teeth that are already broken down or that have had a root canal, because crowns require more reduction.</p><p>Honestly: if bonding can solve it, we will tell you. We have no reason to talk a patient into more work than they need.</p>"),
  ("Materials and labs we use", "<p>For porcelain veneers and full-coverage crowns on front teeth we prefer lithium disilicate (IPS e.max). It is strong enough for most bites and the optics on a properly-shaded e.max veneer are very hard to distinguish from natural enamel. For posterior crowns where bite force is higher, we use zirconia or layered zirconia.</p><p>For composite bonding we use 3M Filtek and Tokuyama Estelite, both well-supported in the clinical literature and easy to polish to a high gloss. Our local lab work for veneers and crowns is sent to a ceramist whose shade-matching we trust enough to put our own family in his hands.</p>"),
  ("What insurance does and does not cover for cosmetic work", "<p>Most Canadian dental insurance plans cover the <em>restorative</em> portion of treatment but not the <em>cosmetic</em> portion. A composite filling that also closes a small diastema is usually covered. A veneer placed purely to change shape or shade is usually not. We submit a pre-authorization with photos and X-rays for any major case so you know what your plan will pay before you commit.</p><p><a href='/canadian-care-dental-plan/'>CDCP</a> does not cover purely cosmetic dentistry. A Health Spending Account through your employer benefits often will, and <a href='/payment-plans/'>Beautifi 0% financing</a> covers the rest.</p>"),
  ("Aftercare that protects the work", "<p>The two things that wreck veneers and front-tooth bonding are night-time grinding and nail-biting. If you grind, a custom night guard ($400 to $650) pays for itself the first time it stops a fracture. We always make one for patients who have visible wear facets or who clench when they are stressed.</p><p>Daily care is otherwise the same as for natural teeth: brush twice, floss or use interdental brushes, and come back every six months so we can polish, check the margins, and catch any early problems while they are easy to fix. Avoid biting hard things directly with the bonded or veneered teeth: pens, ice, fingernails, the corner of a hard pizza crust. Bonding lasts longer on the patients who stop these habits.</p>"),
  ("Red flags when shopping for cosmetic dentistry", "<p>A few things to watch for at any clinic: a quote that does not include a written breakdown of how many teeth and what material, an aggressive push toward veneers when bonding could solve the problem, no mock-up or digital preview before the work begins, no discussion of bite or grinding habits, and pressure to commit on the first visit. Cosmetic dentistry is elective. There is no reason to rush.</p>"),
 ],
 
 },
 "dental-implants": {
 "name": "Dental Implants",
 "short": "Permanent, natural-looking tooth replacement using titanium implants and custom crowns.",
 "intro": "Dental implants replace missing teeth at the root level. Once integrated with your jawbone, the implant supports a custom crown that looks, feels, and functions like a natural tooth.",
 "what_it_is": "A dental implant is a small biocompatible titanium post that's surgically placed in the jawbone. Over a few months it fuses with the bone (osseointegration), then we attach a custom crown, or, for multiple missing teeth, an implant-supported bridge or denture.",
  "sub_services": [
  "Single Tooth Implants",
  "Multiple Implants",
  "Implant-Supported Bridges",
  "Full-Arch Implants",
  "Bone Grafting",
  "Implant Restoration",
 ],
 "good_for": [
 "Replacing one or more missing teeth",
 "Patients tired of removable dentures",
 "Preventing bone loss in the jaw after extraction",
 "Preserving adjacent teeth (no need to grind them down for a bridge)",
 ],
 "process": [
 ("Consultation & 3D scan", "We assess your bone, gums, and bite to confirm you're a candidate."),
 ("Implant placement", "The titanium post is placed in the jawbone under local anesthetic, with sedation if you prefer."),
 ("Healing & integration", "The implant fuses with the bone over 3–6 months."),
 ("Crown placement", "A custom crown is attached, blending perfectly with your natural teeth."),
 ],
 "faqs": [
 ("How long do dental implants last?", "With proper care, dental implants commonly last 20+ years and often a lifetime. The titanium post fuses with your jawbone and is one of the most durable restorations in dentistry. Routine <a href='/services/preventative-dentistry/'>hygiene cleanings</a> and a nightly home-care routine are what keep them healthy long term."),
 ("Is implant surgery painful?", "The procedure is done under local anesthetic, with the option of <a href='/services/nitrous-sedation/'>nitrous oxide sedation</a> if you're anxious. Most patients describe recovery as easier than a routine <a href='/services/oral-surgery/'>tooth extraction</a>, with mild soreness for two to four days that responds well to over-the-counter pain relievers."),
 ("Am I a candidate for dental implants?", "Most healthy adults with sufficient jawbone are candidates. If bone loss is a concern, bone grafting can rebuild the area before implant placement. <a href='/contact-us/'>Book a consultation</a> and we'll review your 3D scan and medical history before recommending a plan."),
 ("How much do dental implants cost in Hamilton?", "A single implant including the crown typically runs $4,000 to $6,000 in Ontario. Cost depends on the number of implants and whether grafting is needed. We provide a clear written estimate after your consultation and offer <a href='/payment-plans/'>Beautifi financing</a> with 0% options on qualifying treatments. <a href='/canadian-care-dental-plan/'>CDCP</a> does not typically cover implants, but private insurance plans often cover part of the crown."),
 ],
 "deep_content": [
  ("How we plan an implant case", "<p>Implants succeed or fail on the planning. Before we place anything we do a 3D cone-beam CT scan of the area to see the bone height, bone width, the position of the inferior alveolar nerve in the lower jaw, and the floor of the maxillary sinus in the upper jaw. We measure the available bone in millimetres and plan the implant length and angle around what is actually there, not what is convenient.</p><p>For most cases we use a surgical guide printed from the scan. The guide drops over your existing teeth and tells the drill exactly where to go and how deep. It is the difference between a precise restoration and one that ends up at the wrong angle, which is a problem you only discover months later when the crown is being made.</p>"),
  ("Brands and components we use", "<p>We work primarily with Straumann and Neodent implants. Both have decades of long-term outcome data, well-established prosthetic libraries, and components your future dentist anywhere in Canada will be able to source if a screw loosens or a crown needs replacement ten years from now. That matters more than people think. Boutique or no-name implant systems can cost less up front but leave you stranded if the manufacturer disappears.</p><p>For the connection between implant and crown we use titanium or zirconia abutments depending on the aesthetic zone, and we cement or screw-retain the crown depending on the case. Screw-retained is easier to repair later if the porcelain ever fractures.</p>"),
  ("When bone grafting is part of the plan", "<p>If a tooth was lost more than a year or two ago, there is usually some bone loss. A small graft (autograft from the area or a particulate xenograft) placed at the same visit as the implant is routine and adds about $500 to $1,500 to the cost depending on the size. A larger ridge augmentation or a sinus lift is a separate procedure done a few months before the implant.</p><p>If your scan shows good bone, you do not need grafting and we will not recommend it.</p>"),
  ("Full-arch options for patients missing many teeth", "<p>For patients losing or already missing most of their upper or lower teeth, the choice is usually between a conventional denture (around $1,800 to $3,200 per arch), an implant-retained denture that snaps onto two to four implants ($6,000 to $12,000), or a fixed full-arch bridge supported by four to six implants, often called All-on-4 ($20,000 to $30,000 per arch). The fixed option feels closest to natural teeth and never comes out. The snap-on option is a major upgrade from a conventional denture at a much lower cost. We walk through both at the consultation along with what your scan can actually support.</p>"),
  ("Implant maintenance and what can go wrong", "<p>The biggest long-term risk to an implant is not the implant itself, it is the gum and bone around it. Peri-implantitis behaves like gum disease around a natural tooth. It is silent in the early stages and can lead to bone loss if not caught. Patients with implants need a hygiene visit every three to four months for the first year or two and at least every six months after that, with a probing check and an annual X-ray on each implant. We use plastic or titanium scalers around implants, never stainless steel, because steel scratches the implant surface and gives bacteria a place to grip.</p>"),
  ("Insurance and CDCP for implants", "<p>Most private dental plans cover the crown portion of an implant (typically 50 percent) but vary widely on the surgical placement. We submit a pre-authorization with the CBCT and treatment plan so the insurer responds in writing with what they will pay. <a href='/canadian-care-dental-plan/'>CDCP</a> does not currently cover implants in most cases, though they cover the underlying extraction if a tooth needs to come out first. <a href='/payment-plans/'>Beautifi financing</a> with 0% options is available for whatever insurance does not cover.</p>"),
 ],
 
 },
 "endodontics": {
 "name": "Endodontics (Root Canals)",
 "short": "Gentle root canal therapy to save infected teeth and relieve severe tooth pain.",
 "intro": "Endodontics treats infection or inflammation inside a tooth's pulp. A root canal removes the damaged tissue, seals the canal, and saves the natural tooth, usually with no more discomfort than a routine filling.",
 "what_it_is": "Root canal therapy is performed when the nerve of a tooth becomes infected from deep decay, cracks, or trauma. Our team uses modern rotary instruments, magnification, and local anesthetic to clean and seal the canal in one to two visits.",
  "sub_services": [
  "Root Canal Therapy",
  "Endodontic Retreatment",
  "Pulp Capping",
  "Emergency Tooth Pain Relief",
 ],
 "good_for": [
 "Severe, lingering toothache",
 "Tooth sensitivity to heat or cold that does not go away",
 "Swelling, pus, or pimple-like bumps on the gum",
 "Deep cracks or large fractures with pulp exposure",
 ],
 "process": [
 ("Diagnosis", "We confirm the tooth needs treatment with an exam and X-ray."),
 ("Anesthetic & access", "The area is fully numbed; a small opening is made in the tooth."),
 ("Cleaning & shaping", "The infected pulp is removed and the canals are cleaned and disinfected."),
 ("Seal & restore", "The canal is sealed and the tooth is typically protected with a crown."),
 ],
 "faqs": [
 ("Does a root canal hurt?", "Modern <a href='/services/endodontics/'>root canal</a> aren't painful, most patients feel relief because the infection causing the pain is being treated."),
 ("Can I avoid extraction?", "Yes. A <a href='/services/endodontics/'>root canal</a> saves your natural tooth, which is almost always preferable to extraction."),
 ("Will I need a crown after?", "Back teeth almost always need a crown afterwards to prevent fracture. Front teeth sometimes don't."),
 ("How many visits will it take?", "Most <a href='/services/endodontics/'>root canal</a> are completed in one or two visits."),
 ],
 "deep_content": [
  ("What a modern root canal actually involves", "<p>The image most people carry of root canals is from the 1970s. The reality in 2026 is unrecognizable. We anaesthetize the tooth (often with a slightly higher dose because infected nerves are harder to numb), place a rubber dam to keep the field clean, and use rotary nickel-titanium files driven by a small motor to clean and shape the canals. An apex locator tells us exactly where the root tip is. We irrigate with sodium hypochlorite and EDTA to dissolve organic debris and break up the bacterial biofilm, then fill the canal three-dimensionally with gutta percha and a bioceramic sealer.</p><p>For most patients the experience is roughly equivalent to a deep filling. The pain is usually before the appointment, not during it. Many leave saying it was easier than they had expected.</p>"),
  ("Why we work hard to save the tooth", "<p>An extraction followed by a single dental implant typically costs $4,000 to $6,000 in Ontario. A root canal plus a crown to protect the tooth runs $1,800 to $3,000. Beyond the cost, your own tooth has a periodontal ligament that lets you feel pressure and temperature in ways an implant never quite does. We default to saving the natural tooth whenever the prognosis is good. We only recommend extraction when the tooth is unrestorable, has a vertical root fracture, or has a poor periodontal prognosis.</p>"),
  ("Single-visit versus multi-visit treatment", "<p>For straightforward cases on front teeth we often finish in a single 60- to 90-minute visit. For molars, infected teeth with abscesses, or canals that are calcified or curved, we usually do the cleaning and shaping at one visit, place a medicated dressing for one to two weeks, then return to finish. The slower path lets the inflammation settle and lowers the chance of post-op flare-ups. Either approach has good long-term success rates in the literature. We tell you which one we are recommending and why at the diagnostic visit.</p>"),
  ("Equipment and imaging we use", "<p>Every operatory has digital X-ray sensors, an apex locator, and magnification (loupes for the routine cases, microscope-level magnification when we need it for calcified or curved canals). For complex cases or retreatment we add a 3D cone-beam CT scan so we can see the root anatomy in three dimensions before opening the tooth. Most failed root canals around the world are not because of bad technique on the original treatment, they are because of an extra canal that was missed. CBCT catches that before the second attempt.</p>"),
  ("What to expect after the appointment", "<p>Most patients feel a dull soreness for two to four days as the ligament around the tooth settles. Ibuprofen 400 mg every six hours works well. The infection that was causing your pain is gone within hours of the appointment, even though the tissue around the tooth takes a few days to calm down. If pain worsens after the third day, swelling appears, or the tooth feels significantly higher than the others when you bite, call us.</p><p>Back teeth almost always need a crown within a few weeks of the root canal to prevent fracture. Front teeth sometimes do not. We will tell you which category your tooth is in.</p>"),
  ("When we refer to an endodontist", "<p>Complex retreatments, badly calcified canals, or cases where surgical intervention (an apicoectomy) is the right answer get referred to a board-certified endodontist. We are honest about the limits of general-practice endodontics. The success rate of a referred case in skilled specialist hands is high enough that the referral is the right call.</p>"),
 ],
 
 },
 "miscellaneous": {
 "name": "Additional Dental Services",
 "short": "Zoom in-office and take-home teeth whitening, sleep-apnea appliances, mouthguards, night guards, and TMJ care.",
 "intro": "Beyond our core services, we offer a range of supportive treatments. This page covers our whitening options (Zoom in-office and custom take-home trays), sleep-apnea appliances, athletic mouthguards, night guards for grinding, TMJ care, and oral cancer screening.",
 "what_it_is": "<strong>Zoom in-office whitening</strong> can lift your shade by 4 to 8 shades in a single 90-minute appointment. A professional-strength gel is activated by a special light over three or four short cycles. Perfect before a wedding, photoshoot, or any big event.<br /><br /><strong>Custom take-home whitening trays</strong> use lower-concentration gel and let you whiten gradually at home over 1 to 2 weeks. You keep the trays for life, top up with new gel any time. Many patients use Zoom for the initial result and take-home trays for touch-ups.<br /><br /><strong>Sleep-apnea appliances</strong> are custom oral appliances that hold the lower jaw slightly forward during sleep to keep the airway open. They are an alternative to CPAP for many patients with mild to moderate obstructive sleep apnea or chronic snoring, and a backup for CPAP intolerance.<br /><br />We also make <strong>custom athletic mouthguards</strong>, <strong>night guards</strong> for bruxism, and treat <strong>TMJ</strong> concerns with bite assessments and conservative therapy.",
  "sub_services": [
  "Zoom In-Office Whitening",
  "Take-Home Whitening Trays",
  "Sleep Apnea Appliances",
  "Anti-Snoring Appliances",
  "Athletic Mouthguards",
  "Night Guards (Bruxism)",
  "TMJ Care",
  "Oral Cancer Screening",
 ],
 "good_for": [
 "Patients who want a dramatic same-day whitening result (Zoom) or gradual home whitening (custom trays)",
 "Snorers and patients with mild to moderate sleep apnea who can't tolerate or don't want CPAP",
 "Athletes who play contact or fast-paced sports",
 "Patients who grind or clench at night, or wake with jaw pain or headaches",
 "Anyone with TMJ symptoms (jaw clicking, pain, limited opening)",
 "Routine oral cancer screening (included with every checkup)",
 ],
 "process": [
 ("Discussion of concerns", "We listen to what's going on and ask the right questions."),
 ("Targeted examination", "Clinical exam, plus digital scans, X-rays, or impressions if useful."),
 ("Whitening or appliance fit", "<a href='/services/miscellaneous/'>Zoom in-office whitening</a> is one 90-minute appointment. Take-home trays, mouthguards, night guards, and sleep-apnea appliances are typically made over two visits from a quick digital scan."),
 ("Follow-up and adjustment", "We check the fit and adjust as needed at no extra charge for the first month."),
 ],
 "faqs": [
 ("How much whiter will my teeth get with Zoom in-office whitening?", "Most patients see 4 to 8 shades of improvement after one Zoom session."),
 ("Zoom or take-home whitening, which is better?", "Zoom is faster and more dramatic. Take-home trays are gradual and easier to control sensitivity. Many patients combine both."),
 ("Will whitening damage my teeth?", "When done under dental supervision, professional whitening is safe and doesn't damage enamel. Mild temporary sensitivity is the most common side effect."),
 ("Can a dental appliance really help with sleep apnea?", "For many patients with mild to moderate obstructive <a href='/services/miscellaneous/'>sleep apnea appliances</a> or chronic snoring, yes. We work with your sleep physician on diagnosis and follow-up."),
 ("How long does a custom night guard last?", "A well-made <a href='/services/miscellaneous/'>night guard</a> typically lasts 3 to 5 years. We adjust the fit as needed."),
 ("Are mouthguards really necessary for sports?", "Yes, for any contact or fast-paced sport. A custom mouthguard fits far better than a boil-and-bite version and protects against concussion as well as broken teeth."),
 ("What can I do about jaw pain?", "We assess your bite, jaw joint, and habits, and start with conservative options like a <a href='/services/miscellaneous/'>night guard</a>, posture changes, and physiotherapy."),
 ("Do you do oral cancer screenings?", "Yes, every checkup includes one at no extra charge."),
 ],
 "deep_content": [
  ("Why these treatments live on one page", "<p>This page bundles a few services that do not need a dedicated landing page but that we do every day: in-office and take-home whitening, oral appliances for sleep apnea and snoring, athletic mouthguards, night guards for grinding, TMJ assessment, and oral cancer screening. They have one thing in common: they are usually decided on at a routine visit rather than searched for by name.</p>"),
  ("TMJ assessment, our approach", "<p>Most jaw pain we see is muscular, not joint-related, and it responds well to conservative care. We start with a bite analysis, a stress and habit conversation (people clench at their desks during work, at the gym during heavy lifts, and while sleeping during stressful weeks), and a custom night guard if the wear pattern on your teeth suggests grinding. We avoid permanent occlusal adjustment or aggressive orthotic devices as a first step. They are not reversible if the diagnosis is wrong, and the diagnosis is wrong more often than you might expect. Patients who do not improve in six to eight weeks of conservative care get a referral to a physiotherapist with TMJ training, and a small minority go on to a TMJ specialist.</p>"),
  ("Sleep apnea oral appliances, when and how", "<p>For mild to moderate obstructive sleep apnea, an oral appliance that holds the lower jaw slightly forward during sleep can be as effective as CPAP and is far easier to live with for patients who cannot tolerate the mask. We do not diagnose sleep apnea ourselves. You need a sleep study (home or in-lab) and a referral or recommendation from your physician or sleep specialist before we make the appliance. Most plans cover oral appliances when prescribed for diagnosed apnea, typically $1,800 to $2,500. We adjust the protrusion in small steps over the first two months and re-check with a follow-up sleep study at the six-month mark.</p>"),
  ("Whitening, the boring honest version", "<p>Professional whitening works on natural enamel. It does not work on crowns, <a href='/services/cosmetic-dentistry/'>veneers</a>, or old fillings, which keep the colour they were the day they were placed. Most patients see four to eight shades of improvement after one Zoom session. If your front teeth have visible old fillings, plan to replace those after whitening so they match the new shade. We will tell you this at the consultation rather than after the bleaching is done. See our <a href='/teeth-whitening-hamilton/'>teeth whitening page</a> for the full breakdown.</p>"),
 ],
 
 },
 "nitrous-sedation": {
 "name": "Nitrous Oxide (Laughing Gas) Sedation",
 "short": "A safe, gentle sedation option that helps anxious patients feel calm and comfortable during dental visits.",
 "intro": "Nitrous oxide sedation, also called laughing gas, helps you relax during dental treatment while remaining fully awake and responsive. It's one of the safest, most well-studied forms of sedation in dentistry.",
 "what_it_is": "You inhale a controlled mix of nitrous oxide and oxygen through a small comfortable nose mask. Within minutes you feel calm and relaxed. When the mask comes off, the effect wears off quickly, and you can drive yourself home.",
  "sub_services": [
  "Nitrous Oxide for Adults",
  "Nitrous Oxide for Children",
  "Sedation for Dental Anxiety",
  "Sedation for Longer Procedures",
 ],
 "good_for": [
 "Patients with dental anxiety or fear",
 "Children who need a little help getting through treatment",
 "Patients with a strong gag reflex",
 "Longer or more involved procedures (implants, surgery, root canals)",
 ],
 "process": [
 ("Pre-visit chat", "We talk through what to expect and confirm nitrous is right for you."),
 ("Mask & settling in", "A soft nose mask delivers the gas; within minutes you feel relaxed."),
 ("Treatment", "Your dentist proceeds with the planned treatment while you stay calm and aware."),
 ("Recovery", "After we switch you to pure oxygen for a few minutes, the effects wear off and you can leave on your own."),
 ],
 "faqs": [
 ("Is nitrous oxide safe?", "Yes, it's one of the safest sedatives in dentistry, used routinely for both adults and children."),
 ("Will I be unconscious?", "No. You remain fully awake and responsive, just more relaxed."),
 ("Can I drive home after?", "Yes. The effects wear off within minutes of removing the mask."),
 ("Is it covered by insurance?", "Many plans cover <a href='/services/nitrous-sedation/'>nitrous sedation</a>. We can verify before your appointment."),
 ],
 "deep_content": [
  ("How nitrous oxide actually works", "<p>You breathe a controlled mix of nitrous oxide and oxygen through a small nose mask. Within two to three minutes you feel a warm, calm, slightly floaty sensation. You are fully awake the whole time. You can talk to us, you remember the visit, and you can drive yourself home minutes after we switch you back to pure oxygen at the end. Nitrous is the lightest, safest sedation option in dentistry, used in millions of appointments every year for both adults and children.</p>"),
  ("Why we offer it as a default option", "<p>Roughly one in three of our patients tells us at some point that they are nervous about the dentist, and many more under-report. Anxiety is the number one reason people delay care and let small problems become large ones. Nitrous removes the barrier without committing you to IV sedation or general anaesthesia. We offer it for routine cleanings, fillings, root canals, extractions, and especially for kids who are getting comfortable with the chair. If you are anxious, tell our receptionist when you book and we will plan the time.</p>"),
  ("Safety and who should not have nitrous", "<p>Nitrous oxide has been studied for over a century. Its safety profile in dental settings is well established. Patients who should not have it: anyone in the first trimester of pregnancy, patients with severe COPD or recent middle-ear surgery, patients on bleomycin chemotherapy, and patients with a vitamin B12 deficiency. We screen for these on your medical history before we use it. If nitrous is contraindicated for you, we use other comfort tools: longer appointments, headphones, topical anaesthetic before the freezing needle, and frequent check-ins.</p>"),
  ("Nitrous for children, our approach", "<p>For children, nitrous is often the difference between a successful first restoration and a long history of avoidance. We start with the lowest effective concentration, talk through what they are feeling, and use it for short appointments only. Most kids tolerate it well and many describe it as a tingly, warm feeling. Parents stay in the room. If a child cannot or will not accept nitrous after a calm introduction, we step back and rebook rather than push. Comfort builds trust and trust pays off across a lifetime of dental visits.</p>"),
  ("Combining nitrous with local anaesthetic", "<p>Nitrous reduces anxiety and softens the gag reflex. It does not numb teeth on its own. For any procedure that needs anaesthesia we still use a local injection, usually with a topical gel first so the needle is barely noticeable. The combination of topical, local anaesthetic, and a low dose of nitrous handles the vast majority of dental procedures comfortably. For longer surgical cases, deeper sedation (oral conscious sedation or IV sedation by a visiting anaesthetist) is occasionally the right choice, and we coordinate that with our surgical referral network.</p>"),
  ("Cost and insurance", "<p>Nitrous oxide sedation is typically $75 to $150 per appointment depending on the length of use. Many private dental insurance plans cover it for procedures where sedation is clinically justified, particularly oral surgery and longer treatments. <a href='/canadian-care-dental-plan/'>CDCP</a> covers nitrous when needed for specific procedures. We confirm coverage before billing.</p>"),
 ],
 
 },
 "oral-surgery": {
 "name": "Oral Surgery & Wisdom Teeth Removal",
 "short": "Safe, precise extractions, wisdom-teeth removal, and minor oral surgery, all in-office.",
 "intro": "We perform most routine oral surgery in our office, including wisdom-teeth removal, complex extractions, biopsies, and pre-prosthetic surgery to prepare for dentures or implants.",
 "what_it_is": "Oral surgery covers any surgical procedure performed in or around the mouth. The most common are wisdom-tooth removal and extractions of severely damaged teeth. We use local anesthetic and offer nitrous oxide sedation to keep you comfortable.",
  "sub_services": [
  "Wisdom Teeth Removal",
  "Tooth Extractions",
  "Surgical Extractions",
  "Pre-Prosthetic Surgery",
  "Biopsies",
  "Cyst Removal",
 ],
 "good_for": [
 "Impacted, painful, or poorly-positioned wisdom teeth",
 "Teeth that can't be saved with a root canal or crown",
 "Preparing for dentures, implants, or orthodontics",
 "Removing cysts or suspicious tissue",
 ],
 "process": [
 ("Consultation & imaging", "A clinical exam and X-ray (or 3D scan) confirms the plan."),
 ("Comfort prep", "Local anesthetic and optional nitrous keep you comfortable."),
 ("Surgery", "The procedure is performed precisely and gently, typically in 30–60 minutes."),
 ("Aftercare", "Detailed home-care instructions, follow-up, and our phone line if you have questions."),
 ],
 "faqs": [
 ("Is wisdom tooth removal painful?", "Not during the procedure, local anesthetic numbs the area completely and <a href='/services/nitrous-sedation/'>nitrous oxide sedation</a> is available if you're anxious. Mild soreness for a few days afterwards is normal and responds well to over-the-counter pain relievers."),
 ("How long is recovery after oral surgery?", "Most patients return to normal activities within 2 to 4 days; full healing takes 1 to 2 weeks. We give you written aftercare instructions and a phone line you can use if anything seems off during recovery."),
 ("Will I need stitches?", "Sometimes. If used, the stitches typically dissolve on their own within a week, so there is no separate visit just for removal."),
 ("Can I drive home after wisdom teeth removal?", "Yes, if only local anesthetic or <a href='/services/nitrous-sedation/'>nitrous sedation</a> is used, you can drive yourself home. If you have IV sedation, you will need a ride."),
 ("How much does wisdom teeth removal cost in Hamilton?", "Cost depends on the number of teeth and whether they are erupted or impacted. We provide a clear written estimate after your consultation. Most private insurance plans cover oral surgery; <a href='/canadian-care-dental-plan/'>CDCP</a> also covers extractions for eligible patients. <a href='/payment-plans/'>Beautifi financing</a> is available for any out-of-pocket portion."),
 ],
 "deep_content": [
  ("How we approach wisdom-tooth removal", "<p>Wisdom teeth fall into three rough categories. Fully erupted and easy to brush teeth that are not causing problems often do not need to come out at all. Partially erupted teeth (covered partly by gum, hard to clean, prone to recurring pericoronitis) usually do. Fully impacted teeth (still buried in bone) come out when they are causing pressure, cyst formation, or damage to the adjacent second molar. We take a 3D cone-beam CT scan when the lower wisdom-tooth roots are close to the inferior alveolar nerve so we can plan the surgery around the nerve rather than guess at it.</p>"),
  ("Recovery timeline, the realistic version", "<p>The first 24 hours: a gauze pad with firm pressure for 30 to 45 minutes, then small soft cold meals (yogurt, mashed avocado, smoothies without a straw), ice packs 15 minutes on and 15 off for the first day, and no rinsing or spitting for the first 24 hours. Days two to four: most patients can return to office work or school, soreness peaks on day two or three and improves from there. Days four to seven: switch to warm salt-water rinses three times a day after meals. Day seven to ten: most of the swelling and bruising is gone, and you can chew normally on the operated side carefully. Full bone healing inside the socket takes three to four months but you will not feel that part.</p>"),
  ("Dry socket, what we do to prevent it", "<p>Dry socket happens when the blood clot that forms in the extraction socket dislodges or fails to form, exposing bone to air. It hurts in a very specific way: a dull ache that radiates to the ear and jaw, starting two to four days after the extraction. We reduce the risk by giving you clear post-op instructions (no smoking for at least 72 hours, no drinking through a straw for 24 hours, no aggressive rinsing for the first day), and for higher-risk patients we sometimes place a slow-release medicated sponge or sutures the day of surgery. If you do develop dry socket, the fix is straightforward: we rinse the socket clean and pack it with a soothing dressing. Pain improves dramatically within hours.</p>"),
  ("When we refer to a maxillofacial surgeon", "<p>Some cases belong with a specialist. Deeply impacted wisdom teeth close to the nerve, patients who need IV sedation or general anaesthesia, severe trauma cases, large cysts, and any patient with significant medical co-morbidities (anticoagulants, bisphosphonates, immunosuppression) often go to one of the maxillofacial surgeons we work with on Hamilton Mountain or downtown. We tell you up front if a case is one we should not do ourselves. Honest scope is part of safe practice.</p>"),
  ("Pre-op and post-op practical notes", "<p>Before surgery: eat a normal breakfast unless we have told you otherwise for sedation. Take any prescribed pre-medications (we will tell you in advance). Wear comfortable clothes. Bring a driver only if you are having sedation beyond nitrous. Plan for one quiet day at home after the surgery. After surgery: keep your head elevated for the first 24 hours, even when sleeping (use an extra pillow). Avoid alcohol and tobacco for at least 72 hours. Take pain medication on a schedule for the first two days rather than waiting for pain. Most patients only need ibuprofen 400 mg every six hours; a small minority need a short course of stronger medication, which we will prescribe at the visit.</p>"),
  ("Cost and insurance for oral surgery", "<p>Simple extractions run $200 to $400 per tooth. Surgical extractions (impacted, broken below the gum, or sectioned) are $400 to $800 per tooth. Bone grafting added at the time of extraction (to preserve the ridge for a future implant) is an additional $400 to $800. Sedation beyond nitrous is billed separately. Private dental insurance covers most oral surgery codes well, often at 80 percent. <a href='/canadian-care-dental-plan/'>CDCP</a> covers extractions, including surgical extractions when needed, for eligible patients. <a href='/payment-plans/'>Beautifi financing</a> is available for any out-of-pocket portion.</p>"),
 ],
 
 },
 "preventative-dentistry": {
 "name": "Preventative Dentistry & Dental Hygiene",
 "short": "Exams, professional cleanings, hygiene, sealants, fluoride, and X-rays that stop dental problems before they start.",
 "intro": "Preventive care is the most effective, and most affordable, kind of dentistry. Regular checkups, professional cleanings with our registered dental hygienists, and personalized home-care coaching catch small issues before they become big ones, saving you time, pain, and money.",
 "what_it_is": "Preventative dentistry at our office includes the full range of preventive and hygiene visits: thorough scaling and polishing by a registered dental hygienist, dental exams, digital X-rays, fluoride treatments, pit and fissure sealants for children, periodontal (gum) charting, oral cancer screenings, and personalized home-care advice. Most patients see us every six months; some need 3- to 4-month intervals based on gum health.",
  "sub_services": [
  "Dental Hygiene & Cleanings",
  "Oral Health & Hygiene Maintenance",
  "Dental Exams & Checkups",
  "Digital X-Rays",
  "Fluoride Treatments",
  "Pit & Fissure Sealants",
  "Diet Counselling",
  "Periodontal Charting",
  "Oral Cancer Screening",
 ],
 "good_for": [
 "Every patient, every age, but especially children and seniors",
 "Routine 6-month dental hygiene cleanings and checkups",
 "Patients with early gum disease (gingivitis) or established periodontal concerns",
 "Patients with crowns, bridges, implants, or aligners that need closer monitoring",
 "Anyone who wants to keep their natural teeth for life",
 ],
 "process": [
 ("Health review", "Your hygienist reviews your medical history and oral-care habits."),
 ("Thorough exam", "Your dentist checks your teeth, gums, bite, joints, and soft tissues."),
 ("X-rays as needed", "Modern digital X-rays use very low radiation and reveal hidden issues."),
 ("Hygiene and cleaning", "Scaling removes tartar buildup, polishing makes teeth feel smooth, and fluoride or sealants protect against future decay."),
 ("Tailored advice", "We discuss what's working well at home, where to focus, and book your next recall."),
 ],
 "faqs": [
 ("How often should I have a dental cleaning?", "Most patients see a hygienist every six months. Patients with gum disease usually need 3- to 4-month intervals to keep it under control."),
 ("Does scaling hurt?", "Modern ultrasonic and hand scaling is gentle. We can numb sensitive spots if needed."),
 ("Why do my gums bleed when I brush?", "Bleeding gums usually mean gingivitis (early gum disease). A professional cleaning plus better home care typically resolves it within a few weeks."),
 ("Are sealants worth it for kids?", "Yes. Sealants prevent the most common type of childhood cavity, the ones on chewing surfaces of molars."),
 ("Do I really need X-rays?", "We only take X-rays when they'll provide useful information. Most adults need a routine set every 1 to 2 years."),
 ("Are cleanings covered by insurance?", "Almost always. Most Canadian plans cover preventive visits, and <a href='/canadian-care-dental-plan/'>CDCP</a> covers preventive care for eligible patients."),
 ],
 "deep_content": [
  ("What gum disease actually looks like in the chair", "<p>Gum disease starts quietly. The earliest sign is bleeding when you brush or floss, which most people incorrectly read as a reason to floss less. The opposite is true. Bleeding gums mean the gum is inflamed because of plaque sitting on the tooth at the gum line, and the only way to stop the bleeding is to clean the area properly for two to three weeks. We measure gum-tissue depth at every checkup with a small probe. Pockets of 1 to 3 mm are healthy. Pockets of 4 to 5 mm indicate early gum disease that is reversible with a deep cleaning. Pockets of 6 mm or more indicate periodontal disease and need more involved treatment.</p>"),
  ("Why we sometimes recommend 3- or 4-month recall", "<p>The default is a hygiene visit every six months. For most healthy adults that is the right interval. Patients with active gum disease, with implants, with orthodontic aligners, or with a history of frequent cavities often do better with three- or four-month visits. The math is simple: a 90-day window is too short for most bacterial colonies to mature back into the disease-causing pattern. A 180-day window in a higher-risk mouth is too long. We do not push closer recalls just to fill the schedule. If your gums are healthy and your home care is solid, we say so and keep you on six months.</p>"),
  ("Sealants and fluoride for kids, when each helps", "<p>Pit-and-fissure sealants are thin protective coatings placed in the deep grooves of permanent molars. They prevent the most common kind of childhood cavity. We place them as soon as the chewing surfaces of the first permanent molars are fully erupted, usually around age six to seven, and again on the second molars around age twelve to thirteen. Fluoride varnish at every recall visit reduces caries risk for kids with high caries activity. For low-risk children we do not over-treat. Sealants and fluoride are both covered by CDCP and most private dental insurance.</p>"),
  ("Diet and dental caries, the practical version", "<p>It is not the total amount of sugar that drives cavities, it is the frequency. A patient who has one daily can of pop with lunch is at much lower risk than a patient who sips a coffee with sugar all morning. Acid is the underlying mechanism, and your saliva needs about thirty minutes to neutralize each acid attack. Five small acid hits separated by ten minutes is more damaging than one larger hit. Practical advice: drink water between meals, not pop or juice. If you do drink something acidic, finish it in one sitting and rinse with water. Brushing immediately after acidic drinks is not ideal; wait twenty to thirty minutes so the enamel can re-mineralize first.</p>"),
  ("Home-care tools that actually work", "<p>The most useful upgrade is interdental brushes for patients with even slightly open spaces between back teeth. They clean more effectively than floss and many patients find them easier to use. Water flossers are helpful for orthodontic patients and for areas around bridges or implants but they do not replace mechanical cleaning at the gum line. A soft- or extra-soft-bristled manual or electric toothbrush is plenty. Hard bristles wear gum tissue and root surfaces. Whitening toothpastes are mostly marketing; the abrasive particles can lift surface stains but they will not change the underlying tooth shade. If anyone is selling you charcoal toothpaste, walk away.</p>"),
  ("Oral cancer screening, the part patients rarely ask about", "<p>Every recall visit at our office includes a short head-and-neck and intraoral cancer screening. We look at the tongue, the floor of the mouth, the soft palate, the lateral borders of the tongue, the lips, and the lymph nodes in the neck. We feel for anything that should not be there. Oral cancers are heavily linked to tobacco, heavy alcohol use, HPV, and sun exposure on the lip. Most are catchable at an early stage when treatment outcomes are excellent. It takes about ninety seconds at every cleaning visit and we never charge separately for it.</p>"),
 ],
 
 },
 "restorative-dentistry": {
 "name": "Restorative Dentistry",
 "short": "Composite (white) fillings, crowns, and bridges that restore strength, function, and appearance.",
 "intro": "Restorative dentistry brings damaged teeth back to full health, strength, and natural appearance. We use tooth-coloured composite fillings for cavities, custom crowns to protect weakened teeth, and bridges to replace missing teeth, all with conservative techniques and modern materials.",
 "what_it_is": "Restorative dentistry includes three main treatments at our office. <strong>Composite (white) fillings</strong> repair cavities and small chips with a tooth-coloured resin that bonds to the tooth and blends with your natural enamel. <strong>Crowns</strong> are custom caps that fully cover a tooth weakened by decay, a fracture, or a root canal. <strong>Bridges</strong> use crowns on the teeth next to a gap to support a replacement tooth in between. We also offer inlays and onlays for medium-sized cavities and implant-supported crowns or bridges for missing teeth.",
  "sub_services": [
  "Composite (White) Fillings",
  "Dental Crowns",
  "Dental Bridges",
  "Inlays & Onlays",
  "Implant-Supported Crowns",
  "Replacing Silver Fillings",
 ],
 "good_for": [
 "Cavities small to large, including replacing old silver amalgam fillings with tooth-coloured composite",
 "Cracked, chipped, or worn teeth from grinding",
 "Teeth weakened by large fillings or a root canal (often need a crown)",
 "Replacing one or more missing teeth with a fixed bridge",
 "Improving the shape, size, or shade of a single tooth",
 ],
 "process": [
 ("Diagnosis and X-rays", "A clinical exam plus digital X-rays show the extent of decay or damage."),
 ("Conservative plan", "We recommend the simplest, most conservative option that will give a durable result: a filling when possible, an inlay/onlay if a filling won't hold, and a crown for larger damage."),
 ("Treatment", "Composite fillings finish in one visit. Crowns and bridges typically need two visits with a temporary in between, made from a digital scan (no goopy impressions)."),
 ("Bite check and follow-up", "We refine your bite, polish the restoration, and review home care before you leave."),
 ],
 "faqs": [
 ("Do you do composite (white) fillings?", "Yes. We use tooth-coloured composite for every new filling and routinely replace old silver amalgam fillings on request."),
 ("How long do composite fillings last?", "With good oral hygiene and regular checkups, <a href='/services/restorative-dentistry/'>composite fillings</a> typically last 7 to 10 years or longer."),
 ("How long do crowns and bridges last?", "Modern porcelain <a href='/services/restorative-dentistry/'>crowns and bridges</a> typically last 10 to 15 years or longer with proper care."),
 ("What is the difference between an inlay, onlay, and crown?", "An inlay sits inside the cusps of a tooth, an onlay covers one or more cusps, and a crown covers the entire tooth. We pick the option that preserves the most healthy tooth structure."),
 ("Will the restoration match my tooth?", "Yes. We shade-match every <a href='/services/restorative-dentistry/'>composite fillings</a>, inlay, onlay, and crown to your natural enamel so the restoration is virtually invisible."),
 ("Is restorative dentistry covered by insurance?", "Most Canadian plans cover restorative work. <a href='/canadian-care-dental-plan/'>CDCP</a> also covers basic restorations for eligible patients. We provide a written estimate before any major treatment."),
 ],
 "deep_content": [
  ("Why we use composite (white) fillings exclusively", "<p>Silver amalgam fillings have a long track record but they expand and contract with temperature differently than tooth structure, which over time can crack the tooth around the filling. They also require more healthy tooth removal to retain mechanically. Modern composite resins bond chemically to the tooth, conserve more healthy structure, and look like part of the tooth instead of part of a machine. They are our default for every new filling. We routinely replace old amalgam fillings on request, particularly when they are showing signs of failure (margin staining, recurrent decay, fracture lines in the surrounding tooth).</p>"),
  ("When a filling becomes a crown", "<p>A filling that covers more than about a third of the chewing surface of a back tooth starts to compromise the long-term survival of the tooth. The tooth flexes under load, and the more of the original chewing surface that is replaced with restorative material, the more it flexes. Once a filling has covered more than two cusps or wraps from one side of the tooth to the other, a crown (or an inlay or onlay) protects the remaining structure far better than another large filling. We will tell you when a tooth has crossed that line. The flip side is also true: we will not crown a tooth that is fine with a filling.</p>"),
  ("Crown materials, what we use and why", "<p>Zirconia crowns are our default for back teeth. They are strong, well-tolerated, and need very little tooth reduction. For visible front teeth we lean toward layered zirconia or lithium disilicate (IPS e.max) for better aesthetics. Porcelain-fused-to-metal (PFM) crowns, which were the standard for decades, are largely obsolete in our practice except for specific bridge work. The dark metal margin that used to appear at the gum line over time is gone with all-ceramic crowns. Crown design is digital, milled or printed from a scan, and the fit is more precise than what an analog impression could deliver ten years ago.</p>"),
  ("Bridges or implants for a single missing tooth", "<p>A three-unit bridge requires the dentist to prepare the two adjacent teeth as anchors, then cement a connected three-tooth restoration. It is faster (two visits over about two weeks) and less expensive than an implant ($2,400 to $4,000 depending on materials). The trade-off is that the two anchor teeth are now linked to the missing-tooth site, and if either of them ever has a problem, the whole bridge has to come off. A single implant leaves the neighbouring teeth completely untouched, and the implant itself is not susceptible to decay. We bias toward implants when the adjacent teeth are healthy and toward bridges when the adjacent teeth already need crowns. Both are valid choices for the right case.</p>"),
  ("Replacing old fillings, when and why", "<p>Fillings do not last forever. Composite fillings average seven to ten years; amalgam fillings often last fifteen to twenty but can crack the tooth around them over time. We replace a filling when the margins are stained or open, when there is recurrent decay under the filling, when the tooth shows a hairline fracture, or when the filling is fractured. We do not replace fillings just because they are old. The first replacement removes more healthy tooth structure than the original placement did, and every subsequent replacement removes more. The honest answer in most cases is: if a 25-year-old amalgam looks fine and the patient has no symptoms, leave it alone.</p>"),
  ("Insurance and CDCP for restorative work", "<p>Composite fillings, crowns, and bridges are all covered to varying degrees by most private dental plans. Fillings are typically 80 percent covered, crowns and bridges are typically 50 percent covered, with an annual maximum that resets each January 1. We pre-authorize any treatment over about $500 so the insurer responds in writing. <a href='/canadian-care-dental-plan/'>CDCP</a> covers fillings and many basic restorative codes for eligible patients. For larger cases that exceed insurance coverage, splitting treatment over two calendar years (the December-January approach) doubles the annual maximum, and <a href='/payment-plans/'>Beautifi financing</a> covers the remainder.</p>"),
 ],
 
 },
 "suresmile-clear-aligners": {
 "name": "SureSmile Clear Aligners",
 "short": "Custom clear-aligner orthodontics that move teeth comfortably and discreetly.",
 "intro": "SureSmile is a clear-aligner system that uses precision-printed aligners to straighten teeth, comfortably, discreetly, and on a clear timeline. It's a great alternative to traditional braces for many adults and teens.",
 "what_it_is": "SureSmile combines digital scanning, 3D treatment planning, and a series of clear aligners worn 20–22 hours a day. Each set moves your teeth a small amount; you progress through the series until your smile is in the planned position.",
  "sub_services": [
  "SureSmile Clear Aligners",
  "Invisalign-Compatible Cases",
  "Bite Refinement",
  "Retainers & Retention",
 ],
 "good_for": [
 "Mild to moderate crowding or spacing",
 "Adults who want a discreet option",
 "Teens with all permanent teeth in place",
 "Patients refining a bite after previous orthodontics",
 ],
 "process": [
 ("Consultation & scan", "A 3D scan replaces traditional impressions, fast and comfortable."),
 ("Digital preview", "You see how your smile will move from start to finish before treatment begins."),
 ("Aligner series", "You wear each set for 1–2 weeks; check-in visits keep things on track."),
 ("Retention", "Custom retainers protect your new smile for the long term."),
 ],
 "faqs": [
 ("How is SureSmile different from Invisalign?", "Both are excellent clear-aligner systems with similar results. We carry both because each fits different cases best, and we will recommend honestly which one suits your bite, timeline, and budget. Curious about <a href='/services/cosmetic-dentistry/'>cosmetic dentistry</a> add-ons to refine your smile after alignment? We can discuss that at your consultation."),
 ("Will SureSmile clear aligners affect my speech?", "Most patients adjust within a few days. A slight lisp on s and th sounds is common at first and fades quickly as your tongue gets used to the trays."),
 ("Can I drink coffee with my aligners?", "Aligners should be removed for anything other than water to avoid staining and damage. Take them out for coffee, tea, juice, and meals, then brush before putting them back in."),
 ("How much do SureSmile clear aligners cost in Hamilton?", "Cost varies by case complexity. We provide a clear estimate up-front and offer <a href='/payment-plans/'>Beautifi financing</a>, including 0% options on qualifying plans. Most private insurance plans cover part of orthodontic treatment; <a href='/canadian-care-dental-plan/'>CDCP</a> generally does not cover orthodontics."),
 ("Are clear aligners a good option for adults?", "Yes. The majority of our clear-aligner patients are adults. They are virtually invisible while you wear them, easy to remove for special occasions, and most cases finish in 6 to 18 months. <a href='/contact-us/'>Book a consultation</a> and we will scan your bite, show you a digital preview of the final result, and explain timing."),
 ],
 "deep_content": [
  ("How SureSmile differs from at-home aligner kits", "<p>Any clear aligner system that ships you trays in the mail with no clinical exam, no X-rays, and no in-person supervision is rolling the dice on your bite. Aligners can damage gum tissue, expose root surfaces, leave the bite uneven, and reveal undiagnosed periodontal disease or root resorption that an in-person exam would have caught. SureSmile is a doctor-supervised system. We take a 3D digital scan, X-rays, and a clinical exam before treatment starts. We design the movements ourselves with the SureSmile software, place small composite attachments on certain teeth when leverage requires it, and see you for short check-ins every six to eight weeks to make sure the movement is tracking. Mid-treatment refinements are part of the plan.</p>"),
  ("Cases we will not take", "<p>Clear aligners handle mild to moderate crowding, mild to moderate spacing, minor bite issues, and post-orthodontic relapse very well. Complex bites (severe overbite, severe underbite, large skeletal discrepancies, certain rotated teeth) are better treated with traditional braces or with surgical orthodontics in some cases. We are honest at the consultation about which group your case falls into. If aligners alone will not give you the result you want, we will say so and refer you to a Hamilton-area orthodontist. We would rather lose the case than over-promise the result.</p>"),
  ("Attachments, IPR, and the things people do not realize aligners do", "<p>Most aligner cases need small tooth-coloured composite bumps (called attachments) on certain teeth. They give the aligner leverage to move that tooth in a specific direction. They come off cleanly at the end of treatment. Some cases also need interproximal reduction (IPR), where we use a very thin diamond file to remove fractions of a millimetre between specific teeth to create space for alignment. Both of these are routine, conservative, and well-tolerated. We explain them at the planning visit so there are no surprises.</p>"),
  ("Compliance, the make-or-break factor", "<p>Aligners need to be worn 20 to 22 hours per day. They come out for eating, drinking anything other than water, and brushing. Patients who consistently wear their aligners full-time finish on schedule. Patients who routinely leave them out for a few hours each evening drag the treatment out by months and sometimes need refinement aligners at the end to finish the case. It is one of the few medical treatments where the patient is genuinely doing more than half of the work. We will tell you the truth about this at the consultation. If a 20-hour daily commitment is not realistic for you, fixed braces are a better fit.</p>"),
  ("Retention is for life", "<p>The biggest mistake in aligner or braces treatment is treating the day the aligners come off as the end of the case. Teeth want to drift back toward where they started, particularly the lower front teeth. We provide a custom retainer (a thin clear retainer for the upper, a small wire bonded to the inside of the lower front teeth or another clear retainer for the lower) and ask you to wear them at night long-term. People who stop wearing retainers usually see relapse within two to five years. People who wear them nightly forever keep their result. The retainers are inexpensive to replace and last for years.</p>"),
  ("Cost and timeline in Hamilton", "<p>Most adult SureSmile cases run $4,500 to $7,500 depending on complexity. Treatment time averages 6 to 12 months for simpler cases, 12 to 18 months for moderate ones, and longer for complex ones. We provide a written estimate after the consultation with photos and a digital preview of the final result so you know roughly what to expect before you commit. Most private orthodontic insurance covers aligner treatment at the same rate as braces, with a lifetime maximum that varies by plan. <a href='/canadian-care-dental-plan/'>CDCP</a> generally does not cover orthodontics. <a href='/payment-plans/'>Beautifi financing</a> with 0% options on qualifying treatments is available for any out-of-pocket portion.</p>"),
 ],
 
 },
}

# Team members: slug -> data
# Doctors (canonical at /team/, with /about/ canonical-redirecting to /team/)
TEAM = {
 "dr-fadi-dawood": {
 "name": "Dr. Fadi Dawood",
 "role": "Owner",
 "photo": "695fc139ba075a99589a81cc_Owner.png",
 "bio": [
 "Dr. Fadi Dawood is the owner of Hamilton Care Dental Centre. He founded the practice in 2012 with a simple goal: deliver thorough, gentle dentistry that treats every patient like family.",
 "Patients consistently describe Dr. Dawood as patient, thorough, and genuinely caring. He focuses on family dentistry, dental implants, and complex restorative cases.",
 ],
 },
 "dr-bassam-petros": {
 "name": "Dr. Bassam Petros",
 "role": "Dentist",
 "photo": "695fc16d95d4cc3dcb72b1e8_Associate_Dentist.png",
 "bio": [
 "Dr. Bassam Petros is an associate dentist at Hamilton Care Dental Centre. He treats patients of all ages and is particularly known for his gentle chairside manner with children and anxious patients.",
 "Dr. Petros provides thorough care including preventive dentistry, cosmetic treatments, restorative work, and clear-aligner orthodontics.",
 ],
 },
 "dr-peter-markho": {
 "name": "Dr. Peter Markho",
 "role": "Associate Dentist",
 "photo": "petermarkho.png",
 "bio": [
 "Dr. Peter Markho is an associate dentist at Hamilton Care Dental Centre. He provides general and cosmetic dental services for patients across Hamilton.",
 "Dr. Markho is committed to ongoing education and to using current, evidence-based techniques to deliver clear, conservative care.",
 ],
 },
 "maha": {
 "name": "Maha",
 "role": "Dental Assistant",
 "photo": "69544ac938513c9b12f2de96_Maha.JPEG",
 "bio": [
 "Maha is a dental assistant at Hamilton Care Dental Centre. She works closely with our dentists during procedures and is known for her calm, reassuring presence.",
 "Maha is often one of the first faces patients see in the operatory, and one of the reasons so many of our reviews mention how comfortable they felt during treatment.",
 ],
 },
 "makayla": {
 "name": "Makayla",
 "role": "Dental Assistant",
 "photo": "69544ac938513c9b12f2de81_Makayla.JPEG",
 "bio": [
 "Makayla is a dental assistant who supports the team during a wide range of procedures, from routine cleanings to implant surgery.",
 "She is friendly, organized, and dedicated to making every patient feel at ease.",
 ],
 },
 "viktoriya": {
 "name": "Viktoriya",
 "role": "Dental Assistant",
 "photo": "69544ac938513c9b12f2de97_Vikoriya.JPEG",
 "bio": [
 "Viktoriya is a dental assistant at Hamilton Care Dental Centre. She helps coordinate appointments, prepares treatment rooms, and assists chairside during procedures.",
 "Her attention to detail and warm communication help make every visit smooth.",
 ],
 },
 # /team/ only members
 "darcy": {
 "name": "Darcy",
 "role": "Registered Dental Hygienist",
 "photo": "695fc64490e9e79261cb959f_Darcy.png",
 "bio": [
 "Darcy is a registered dental hygienist at Hamilton Care Dental Centre. She provides thorough, gentle cleanings, periodontal care, and personalized home-care coaching.",
 "Many of our long-term patients see Darcy every six months, and she is a big reason they keep coming back.",
 ],
 },
 "erazel": {
 "name": "Erazel",
 "role": "Dental Assistant",
 "photo": "erazel.png",
 "bio": [
 "Erazel is a dental assistant at Hamilton Care Dental Centre. She works chairside with our dentists across general, cosmetic, and surgical procedures.",
 "Patients often mention how comfortable she helps them feel, especially during longer appointments. Her calm, attentive style sets the tone for a smooth visit.",
 ],
 },
 "fatima": {
 "name": "Fatima",
 "role": "Dental Receptionist",
 "photo": "695fc3d46c849965cb0aeba0_Fatima.png",
 "bio": [
 "Fatima is a dental receptionist at Hamilton Care Dental Centre. She welcomes patients, books appointments, and handles insurance questions and CDCP claims so every visit starts smoothly.",
 "She is fluent at navigating Canadian dental insurance and the Canadian Dental Care Plan, and works hard to make care as affordable and predictable as possible.",
 ],
 },
 "lucy": {
 "name": "Lucy",
 "role": "Assistant Office Manager",
 "photo": "695fc36600851c5991192f35_Lucy.jpg",
 "bio": [
 "Lucy is our Assistant Office Manager. She supports the day-to-day running of the practice, helps coordinate the schedule, and keeps things moving for our front-office and clinical teams.",
 "Her warm welcome is often the first thing patients mention in our reviews.",
 ],
 },
 "maheen": {
 "name": "Maheen",
 "role": "Registered Dental Hygienist",
 "photo": "695fc4f744be23b3ad24c69d_Maheen.png",
 "bio": [
 "Maheen is a Registered Dental Hygienist at Hamilton Care Dental Centre. She delivers gentle, thorough cleanings and personalized home-care coaching for patients of every age.",
 "She is known for her calm chairside manner and her attention to detail with periodontal care.",
 ],
 },
 "melissa": {
 "name": "Melissa",
 "role": "Registered Dental Hygienist",
 "photo": "695fc52d311f8540d54a3aba_Melissa.png",
 "bio": [
 "Melissa is a Registered Dental Hygienist focused on gentle preventive care and patient education.",
 "She shapes home-care routines to each patient's needs, including those wearing braces, clear aligners, or implants.",
 ],
 },
 "nahrin": {
 "name": "Nahrin",
 "role": "Dental Receptionist",
 "photo": "695fc3a74c192fae4f9469aa_Nahrin.jpg",
 "bio": [
 "Nahrin is a dental receptionist at Hamilton Care Dental Centre. She handles bookings, follow-up calls, and insurance questions so patients always know what to expect before their visit.",
 "Her organized, friendly style keeps the schedule running on time.",
 ],
 },
 "paeez": {
 "name": "Paeez",
 "role": "Dental Assistant",
 "photo": "695fc40212b44ca167596e2b_Paeez.png",
 "bio": [
 "Paeez is a dental assistant at Hamilton Care Dental Centre. He works chairside with our dentists across general and surgical procedures and helps every appointment run smoothly.",
 "Patients appreciate his calm, helpful approach and his attention to comfort during longer treatments.",
 ],
 },
 "saif": {
 "name": "Saif",
 "role": "Denturist",
 "photo": "695fc28fb77fe3cc807785ae_Saif.jpg",
 "bio": [
 "Saif is the denturist at Hamilton Care Dental Centre. He designs and fits complete and partial dentures, immediate dentures, and implant-retained dentures right in our office.",
 "Working on-site means faster turnaround, better aesthetics, and tight coordination with our dental team for extractions, implants, and follow-up adjustments.",
 ],
 },
 "sally": {
 "name": "Sally",
 "role": "Registered Restorative Dental Hygienist & Office Manager",
 "photo": "695fc30246bc7e1590459662_Sally.png",
 "bio": [
 "Sally is our Office Manager and a Registered Restorative Dental Hygienist. She splits her time between leading the office team and providing thorough hygiene visits and restorative care for patients.",
 "Her cheerful, organized approach sets the tone for the whole practice.",
 ],
 },
 "sana": {
 "name": "Sana",
 "role": "Dental Assistant",
 "photo": "695fc471b77fe3cc80788b19_Sana.png",
 "bio": [
 "Sana is a dental assistant at Hamilton Care Dental Centre. She supports our dentists chairside across general, cosmetic, and surgical procedures.",
 "Patients appreciate her gentle approach and the way she keeps them informed throughout each step.",
 ],
 },
 "torees": {
 "name": "Torees",
 "role": "Registered Dental Hygienist",
 "photo": "695fc4a2e6fcbb9f696acf41_Torees.jpg",
 "bio": [
 "Torees is a Registered Dental Hygienist at Hamilton Care Dental Centre. She delivers gentle cleanings and periodontal care, with a focus on long-term gum health.",
 "She is known for keeping patients informed and comfortable throughout every appointment.",
 ],
 },
}


# Blog posts: slug -> data. Original copy.
# Date format: ISO 8601
BLOG = {
 "canadian-dental-care-plan-cdcp----how-hamilton-care-dental-supports-it": {
 "title": "Canadian Dental Care Plan (CDCP): How Hamilton Care Dental Supports It",
 "seo_title": "CDCP in Hamilton: How We Support Patients",
 "date": "2026-02-20",
 "hero": "69544ac938513c9b12f2dded_Dentists-Denturistour-story-1024x1024.png",
 "summary": "The Canadian Dental Care Plan helps eligible Canadians afford dental care. Here's what it covers, who qualifies, and how Hamilton Care Dental supports CDCP patients.",
 "keywords": "CDCP Hamilton, Canadian Dental Care Plan, dental insurance Hamilton, affordable dentist Hamilton",
 "body": [
 ("What is the CDCP?", "The <a href='/canadian-care-dental-plan/'>Canadian Dental Care Plan</a> (<a href='/canadian-care-dental-plan/'>CDCP</a>) is a federal program that helps eligible Canadians cover the cost of dental care. It's administered through Sun Life and covers a wide range of routine and restorative treatments. Hamilton Care Dental Centre is proud to accept <a href='/canadian-care-dental-plan/'>CDCP</a> for all eligible patients."),
 ("Who qualifies?", "<a href='/canadian-care-dental-plan/'>CDCP</a> is available to Canadian residents without private dental insurance whose adjusted family net income is below the program threshold. Eligibility expanded in 2025 to include most adults under 65 in addition to seniors and children. You can confirm your eligibility on the Government of Canada <a href='/canadian-care-dental-plan/'>CDCP</a> page."),
 ("What does CDCP cover?", "Covered services include exams, cleanings, X-rays, fillings, extractions, <a href='/services/miscellaneous/'>dentures</a>, <a href='/services/endodontics/'>root canal</a>, and many restorative treatments. Some treatments may require pre-authorization. We'll explain exactly what's covered before any treatment begins so there are no surprises."),
 ("How we make CDCP simple", "We submit all claims directly to Sun Life on your behalf. There is no paperwork for you to fill out, and your co-pay (if any) is collected at the appointment. If you have questions about coverage, our treatment coordinators can walk you through it before you book."),
 ("Booking a CDCP appointment", "Call us at (289) 755-2568 or <a href='/contact-us/'>book online</a>. Have your <a href='/canadian-care-dental-plan/'>CDCP</a> member ID number handy and we will take care of the rest."),
 ],
 },
 "dental-benefits-in-2026-use-your-insurance-early-beautifi-0-financing-for-a-more-confident-smile-in-hamilton": {
 "title": "Dental Benefits in 2026: Use Your Insurance Early + Beautifi 0% Financing in Hamilton",
 "seo_title": "Use 2026 Dental Benefits Early + Beautifi 0% Financing",
 "date": "2026-04-22",
 "hero": "6a04c1d25217f5426cd9cbe6_beautify_financing.webp",
 "summary": "Most Canadian dental plans reset annually. Here's how to use your 2026 benefits early, and how Beautifi 0% financing covers what insurance doesn't.",
 "keywords": "dental insurance 2026, Beautifi financing Hamilton, dental payment plans, affordable dentistry Hamilton",
 "body": [
 ("Your dental benefits reset every year", "Most Canadian private dental plans reset their annual maximum on January 1. Any unused benefits from the previous year are gone, they don't roll over. The patients who get the most value from their plan are the ones who book early in the year."),
 ("Why booking in Q1 is smart", "Early in the year, your full annual maximum is available. If you need restorative work, splitting it across two calendar years can let you use the maximum twice, once in December, again in January, covering a larger portion of treatment."),
 ("What if treatment costs more than my insurance covers?", "We offer <a href='/payment-plans/'>Beautifi financing</a>, flexible monthly payment plans, including 0% options on qualifying treatments. There's no penalty for early repayment, and applications take just a few minutes."),
 ("Combining insurance + financing", "Patients regularly use insurance to cover the diagnostic and restorative portion of treatment, then use Beautifi for cosmetic or elective parts (whitening, <a href='/services/cosmetic-dentistry/'>veneers</a>, Invisalign). Together, you get the smile you want with predictable monthly payments."),
 ("Get a clear estimate first", "Before any major treatment, we provide a written estimate showing what insurance is likely to pay and what your out-of-pocket cost would be. <a href='tel:+12897552568'>Call (289) 755-2568</a> or <a href='/contact-us/'>book online</a> to start the conversation."),
 ],
 },
 "dentist-near-me-on-hamilton-mountain-your-local-dental-clinic-on-upper-ottawa": {
 "title": "Dentist Near Me on Hamilton Mountain: Your Local Dental Clinic on Upper Ottawa",
 "seo_title": "Dentist Near Me on Hamilton Mountain (Upper Ottawa)",
 "date": "2026-05-13",
 "hero": "69dd355bbbc53f8d5f980cf0_hamilton-care-denta-centre-new-patients.jpg",
 "summary": "Looking for a trusted dentist on Hamilton Mountain? Here's why families across Upper Ottawa, Stoney Creek, and Ancaster choose Hamilton Care Dental Centre.",
 "keywords": "dentist near me Hamilton Mountain, Hamilton dentist, Upper Ottawa dentist, family dentist Hamilton",
 "body": [
 ("Right in the heart of Hamilton Mountain", "Hamilton Care Dental Centre sits on Upper Ottawa Street, easy to reach from Mountain neighbourhoods, Stoney Creek, Ancaster, and Dundas. We have free parking right at the unit and plenty of natural light inside."),
 ("Thorough care under one roof", "From routine cleanings and check-ups to <a href='/services/dental-implants/'>dental implants</a>, Invisalign, <a href='/services/oral-surgery/'>oral surgery</a>, and emergency care, almost everything you need is provided in-office. That means fewer referrals out and less time off work for you."),
 ("Family-friendly, all-ages care", "We see toddlers having their first checkup, teens in Invisalign, busy parents getting cleanings, and seniors restoring their smiles. Patients love that the whole family can be seen in one office."),
 ("Same-day and emergency appointments", "If you're in pain, call us first. We hold time every day for emergencies, broken teeth, severe pain, lost fillings, swelling, and aim to see you the same day."),
 ("Booking and contact", "<a href='tel:+12897552568'>Call (289) 755-2568</a>, email office@hamiltoncaredental.ca, or <a href='/contact-us/'>book online</a>. We're open Monday–Friday 8–6 and Saturday 9–3."),
 ],
 },
 "emergency-dentist-near-me-in-hamilton-same-day-care": {
 "title": "Emergency Dentist Near Me in Hamilton: Same-Day Care When You Need It",
 "seo_title": "Emergency Dentist in Hamilton: Same-Day Care",
 "date": "2026-05-09",
 "hero": "69dd3551d20cffd06b71bc71_emergency-dental-hamilton-care-dental-centre.jpg",
 "summary": "Severe tooth pain, a broken tooth, swelling, or a lost filling? Here's what to do, and how Hamilton Care Dental Centre handles dental emergencies.",
 "keywords": "emergency dentist Hamilton, same-day dental Hamilton, tooth pain Hamilton, broken tooth Hamilton",
 "body": [
 ("What counts as a dental emergency?", "Severe tooth pain, swelling, a knocked-out tooth, a broken tooth with sharp edges, a lost filling or crown that's exposing nerve, and uncontrolled bleeding all qualify as dental emergencies. Don't wait, call us right away."),
 ("First-aid steps before you arrive", "Rinse with warm salt water for pain and infection. Apply cold compress to the outside of the cheek for swelling. For a knocked-out tooth, gently rinse it (don't scrub), and store it in milk or your own saliva until you get to us."),
 ("How we handle emergencies", "<a href='tel:+12897552568'>Call (289) 755-2568</a>, even after hours, our message will tell you the best way to reach us. During business hours we hold appointment slots for emergencies and aim to see you the same day."),
 ("Common emergency treatments", "We provide pain relief, drainage of infections, temporary crowns, emergency <a href='/services/endodontics/'>root canal</a>, extractions, and stabilization of broken teeth. For most emergencies you can be comfortable within an hour or two of arriving."),
 ("Cost and insurance for emergencies", "Most dental insurance plans cover emergency exams and treatment. <a href='/canadian-care-dental-plan/'>CDCP</a> also covers emergency care for eligible patients. We provide a clear cost estimate before treatment."),
 ],
 },
 "how-much-does-dental-care-cost-in-hamilton-what-patients-should-expect-in-2025": {
 "title": "How Much Does Dental Care Cost in Hamilton? What to Expect in 2025",
 "seo_title": "Dental Care Costs in Hamilton: 2025 Patient Guide",
 "date": "2026-04-08",
 "hero": "69544ac938513c9b12f2dde4_Untitled-design-17-min-555x740.png",
 "summary": "A clear, honest look at dental costs in Hamilton, checkups, fillings, crowns, implants, Invisalign, and how insurance, CDCP, and financing help.",
 "keywords": "dental costs Hamilton, dentist prices Hamilton, dental fee guide 2025 Ontario, affordable dentist Hamilton",
 "body": [
 ("Where dental fees come from", "Most Ontario dentists base their fees on the Ontario Dental Association (ODA) fee guide. The guide is updated annually and lists a suggested fee for every dental code. Your fee may vary slightly depending on the complexity of your case."),
 ("Routine care", "A new-patient exam, cleaning, and X-rays typically falls in the $200–$350 range. Recall (6-month) exams plus a cleaning are usually $150–$250. <a href='/canadian-care-dental-plan/'>CDCP</a> and most private insurance cover these visits."),
 ("Restorations", "A composite (white) filling ranges from $150 to $350 depending on size and location. A porcelain crown is typically $1,200–$1,800. A <a href='/services/endodontics/'>root canal</a> ranges from $700 (front tooth) to $1,500 (molar), plus a crown afterwards for back teeth."),
 ("Implants and orthodontics", "A single <a href='/services/dental-implants/'>dental implants</a> including the crown typically runs $4,000–$6,000 in Ontario. Invisalign and <a href='/services/suresmile-clear-aligners/'>SureSmile clear aligners</a> range from $4,500 to $8,500 depending on case complexity."),
 ("How to make care affordable", "Insurance covers a large share of routine and restorative care. <a href='/canadian-care-dental-plan/'>CDCP</a> covers eligible patients for most basic services. For the rest, <a href='/payment-plans/'>Beautifi financing</a> offers flexible monthly plans. Ask for a written estimate before any major treatment, you should never be surprised by the bill."),
 ],
 },
 "how-often-should-you-visit-the-dentist-what-the-experts-recommend": {
 "title": "How Often Should You Visit the Dentist? What the Experts Recommend",
 "seo_title": "How Often Should You Visit the Dentist?",
 "date": "2026-01-08",
 "hero": "6956260aec543390f64c4164_istockphoto-2203896947-612x612-1.jpg",
 "summary": "Most people are told 'every six months', but is that right for you? Here's what the evidence and experts say about ideal dental visit frequency.",
 "keywords": "how often dentist visit, dental checkup frequency, preventive dentistry Hamilton",
 "body": [
 ("The standard recommendation", "The Canadian Dental Association recommends a checkup and professional cleaning every six months for most healthy adults. This catches small problems early, when they are easier and cheaper to fix, and keeps gum disease in check."),
 ("Why six months?", "Six months is short enough that most early cavities can be detected before they reach the nerve, and that tartar buildup can be removed before it causes gum disease. It's long enough that visits don't become a hassle for most patients."),
 ("When you might need more frequent visits", "Patients with active gum disease often need a cleaning every 3–4 months. Patients with crowns, bridges, implants, or aligners benefit from closer monitoring. So do patients who grind their teeth or who have a history of frequent cavities."),
 ("When less-frequent visits might be reasonable", "Some patients with excellent home care, no gum disease, and very low caries risk may safely extend to 9 or 12 months. We will tell you honestly if you fit that category."),
 ("How to know what's right for you", "At your next visit, ask your dentist directly: 'What recall interval is right for me?' We will give you a real answer based on your gums, your habits, and your history, not a one-size-fits-all schedule."),
 ],
 },
 "preventive-dentistry-in-hamilton-how-regular-care-saves-you-time-pain-money": {
 "title": "Preventive Dentistry in Hamilton: How Regular Care Saves You Time, Pain, and Money",
 "seo_title": "Preventive Dentistry in Hamilton: Save Time and Money",
 "date": "2026-02-06",
 "hero": "69544ac938513c9b12f2dded_Dentists-Denturistour-story-1024x1024.png",
 "summary": "Skipping dental visits to save money is one of the most expensive choices you can make. Here's how preventive care pays off, financially and in quality of life.",
 "keywords": "preventive dentistry Hamilton, dental cleanings Hamilton, dental exam Hamilton, oral health prevention",
 "body": [
 ("The cost of skipping care", "A routine cleaning costs roughly $150. A filling on the same tooth a year later, after a cavity has formed, costs $200–$350. If the cavity reaches the nerve and needs a <a href='/services/endodontics/'>root canal</a> plus crown, you're looking at $2,500+. The math heavily favours prevention."),
 ("What preventive dentistry actually does", "Regular cleanings remove tartar that you can't remove at home, which is the root cause of most gum disease. Routine exams catch cavities, cracks, oral cancers, and worn teeth before they need expensive treatment."),
 ("Beyond the teeth", "Gum disease is linked to cardiovascular disease, diabetes complications, and adverse pregnancy outcomes. Keeping your gums healthy supports the rest of your body, too."),
 ("Home care that multiplies the value of your visits", "Brush twice a day with fluoride toothpaste. Floss or use interdental brushes daily. Limit sticky sweets between meals. Drink water through the day. None of this is fancy, but consistently doing it dramatically reduces dental problems."),
 ("Booking your preventive visit", "If it's been more than a year, book now. <a href='tel:+12897552568'>Call (289) 755-2568</a> or schedule online. <a href='/canadian-care-dental-plan/'>CDCP</a> and most insurance cover preventive care fully."),
 ],
 },
 "the-technology-behind-your-smile-how-modern-dentistry-is-changing-the-game": {
 "title": "The Technology Behind Your Smile: How Modern Dentistry Is Changing the Game",
 "seo_title": "The Technology Behind Your Smile",
 "date": "2026-03-10",
 "hero": "69823a60259f0beff7e0e59d_IMG_1932.JPG",
 "summary": "Digital X-rays, intraoral scanners, 3D printing, clear aligners, modern dentistry looks nothing like it did 20 years ago. Here's what's actually new.",
 "keywords": "modern dental technology, digital dentistry Hamilton, intraoral scanner Hamilton, 3D dental printing",
 "body": [
 ("Digital X-rays", "Digital sensors capture images instantly with up to 90% less radiation than traditional film. The images appear on a screen the moment they are taken, so we can review them with you chairside."),
 ("Intraoral scanners", "Goopy impression trays are largely a thing of the past. A small wand scans your teeth in seconds, building a precise 3D model that goes straight to the lab, faster results, more accurate restorations, and a more comfortable experience."),
 ("3D treatment planning", "For implants, orthodontics, and complex restorations, we plan the entire treatment digitally before touching a tooth. You see a preview of the final result, and the surgery or aligner sequence is optimized for predictability."),
 ("Clear aligners", "Clear aligners like Invisalign and <a href='/services/suresmile-clear-aligners/'>SureSmile clear aligners</a> use 3D scanning and high-precision printing to move teeth in a controlled sequence, discreet, comfortable, and removable."),
 ("Why this matters for patients", "Faster appointments, less discomfort, better-fitting restorations, and clearer communication. Technology in dentistry isn't about gadgets, it's about better outcomes for patients."),
 ],
 },
 "why-families-in-hamilton-choose-hamilton-care-dental-centre": {
 "title": "Why Families in Hamilton Choose Hamilton Care Dental Centre",
 "seo_title": "Why Hamilton Families Choose Hamilton Care Dental",
 "date": "2026-05-05",
 "hero": "69544ac938513c9b12f2ddec_IMG_7577-Edited-min-1024x683.jpg",
 "summary": "From toddlers to grandparents, we treat the whole family under one roof. Here's what families consistently tell us they appreciate.",
 "keywords": "family dentist Hamilton, best dentist Hamilton families, Hamilton family dental clinic",
 "body": [
 ("One office for the whole family", "Parents save time by booking kids and adults together. We coordinate appointments so the whole family can be seen in one visit, and we have streaming on the ceiling in some rooms to keep little ones distracted."),
 ("Patient, gentle care for kids", "Kids' first dental visits set the tone for life. Our team takes the time to build trust, counting teeth, showing tools, and never rushing. We don't push treatment that can wait."),
 ("Senior-friendly", "Many seniors come to us for <a href='/services/miscellaneous/'>dentures</a>, implants, and complex restorative work. Direct billing and <a href='/canadian-care-dental-plan/'>CDCP</a> support make care accessible."),
 ("Family logistics, sorted", "Direct insurance billing, evening and Saturday hours, free parking, plenty of natural light, and an office that doesn't feel sterile. Small things that add up to a better experience."),
 ("A 4.9-star average from 89+ reviews", "Patients consistently mention three things in their reviews: gentle care, honest recommendations, and a friendly team. That's the practice we set out to build."),
 ],
 },
 "wisdom-teeth-removal-near-me-in-hamilton-expert-oral-surgery-on-hamilton-mountain": {
 "title": "Wisdom Teeth Removal in Hamilton: Expert Oral Surgery on Hamilton Mountain",
 "seo_title": "Wisdom Teeth Removal in Hamilton: Oral Surgery",
 "date": "2026-01-22",
 "hero": "69dd357ddd5316a68625f91e_wisdom-teeth-removal-hamilton-care-dental-centre.jpg",
 "summary": "Most adults need wisdom teeth out at some point. Here's how to know when, what the procedure is like, and how recovery actually goes.",
 "keywords": "wisdom teeth removal Hamilton, oral surgery Hamilton Mountain, wisdom tooth extraction Hamilton",
 "body": [
 ("When wisdom teeth need to come out", "Most patients need wisdom teeth removed between ages 17 and 25, before the roots are fully formed. Common reasons: impaction (the tooth can't fully erupt), crowding adjacent teeth, infection or cysts, or repeated gum inflammation."),
 ("Sedation options", "We perform wisdom tooth removal under local anesthetic, with nitrous oxide (laughing gas) sedation for added comfort. For more complex cases, IV sedation is available with our anesthetist."),
 ("What recovery looks like", "Mild swelling and soreness for 2–4 days. Most patients return to school or office work within 3 days. Avoid hard, crunchy, or sticky foods for the first week and don't smoke during healing."),
 ("Cost and insurance", "Wisdom-tooth removal is covered by most Canadian dental plans, including <a href='/canadian-care-dental-plan/'>CDCP</a>. We provide a written estimate before surgery. <a href='/payment-plans/'>Beautifi financing</a> is available for any out-of-pocket costs."),
 ("Booking a consultation", "We start with a panoramic X-ray or 3D scan to see the position of the teeth. From there we explain your options. <a href='tel:+12897552568'>Call (289) 755-2568</a> to book a consultation."),
 ],
 },
 "your-smile-your-confidence-the-rise-of-cosmetic-dentistry-in-hamilton": {
 "title": "Your Smile, Your Confidence: The Rise of Cosmetic Dentistry in Hamilton",
 "seo_title": "Cosmetic Dentistry in Hamilton: Confident Smiles",
 "date": "2026-03-24",
 "hero": "69575bb957af7f49684deea5_Screenshot-2025-04-14-112747.png",
 "summary": "Cosmetic dentistry has gone mainstream, and it's not just about veneers. Here's what's possible, what's realistic, and how to choose what's right for you.",
 "keywords": "cosmetic dentistry Hamilton, smile makeover Hamilton, veneers Hamilton, teeth whitening Hamilton",
 "body": [
 ("Why cosmetic dentistry is booming", "Smartphone cameras, video calls, and social media have made everyone more aware of their smile. At the same time, modern materials, <a href='/services/cosmetic-dentistry/'>veneers</a>, durable composite, predictable whitening, have made beautiful, natural-looking results more accessible than ever."),
 ("Conservative first", "We always recommend the least invasive option that will achieve your goal. For many patients, that's professional whitening plus a few hours of composite bonding, not full <a href='/services/cosmetic-dentistry/'>veneers</a>."),
 ("Common cosmetic treatments", "Professional whitening (Zoom or take-home), composite bonding for chips and gaps, <a href='/services/cosmetic-dentistry/'>veneers</a> for major changes in shape and shade, Invisalign or <a href='/services/suresmile-clear-aligners/'>SureSmile clear aligners</a> for alignment, gum recontouring for gummy smiles, and tooth-coloured crowns to replace old metal restorations."),
 ("How long results last", "Whitening lasts 1–3 years. Composite bonding lasts 5–10 years and can be touched up. Porcelain <a href='/services/cosmetic-dentistry/'>veneers</a> last 10–15 years on average."),
 ("Booking a smile consultation", "Cosmetic consultations are relaxed, we listen to your goals, take photos, and explain real options with real costs. <a href='tel:+12897552568'>Call (289) 755-2568</a> or <a href='/contact-us/'>book online</a>."),
 ],
 },
}
