"""Original page content for Hamilton Care Dental Centre site rebuild.

All body copy is written originally for this rebuild based on general dental
domain knowledge. Hero images are sourced from the practice's own assets
(downloaded into /assets/images/scraped/). Business identifiers (NAP, dentist
names, service names) are factual and reused as-is.
"""

# Map: page slug -> hero filename (in /assets/images/scraped/) OR fallback hero in /assets/images/
HERO_MAP = {
 # Core pages
 "about-us": "696866587ed8f107ea46c01d_IMG_7592.CR3_compressed.JPEG",
 "our-story": "696866587ed8f107ea46c01d_IMG_7592.CR3_compressed.JPEG",
 "services": "69823a60259f0beff7e0e59d_IMG_1932.JPG",
 "contact-us": "696869207a6acaa7ac1d368d_IMG_7577-Edited-min-2048x1365.jpg",
 "new-patients": "696869207a6acaa7ac1d368d_IMG_7577-Edited-min-2048x1365.jpg",
 "blog": "69dd357ddd5316a68625f91e_wisdom-teeth-removal-hamilton-care-dental-centre.jpg",
 "payment-plans": "6a04c1d25217f5426cd9cbe6_beautify_financing.webp",
 "canadian-care-dental-plan": "69544ac938513c9b12f2dded_Dentists-Denturistour-story-1024x1024.png",
 "referral-form": "69544ac938513c9b12f2dde5_Untitled-design-14-min-555x740.png",
 "thank-you": "69544ac938513c9b12f2dde5_Untitled-design-14-min-555x740.png",
 "privacy-policy": "69544ac938513c9b12f2dde4_Untitled-design-17-min-555x740.png",
 "style-guide": "69544ac938513c9b12f2dde5_Untitled-design-14-min-555x740.png",

 # Service detail pages
 "cosmetic-dentistry": "cos1.png",
 "dental-implants": "698237a0315ecee2c52c1f82_istockphoto-1811278606-612x612.jpg",
 "endodontics": "endodontics.jpg",
 "miscellaneous": "m1.png",
 "nitrous-sedation": "nitrous-sedation.jpg",
 "oral-surgery": "69575b656e3432c4987283e6_PICT0184.jpg",
 "preventative-dentistry": "prev1.jpg",
 "restorative-dentistry": "rest1.png",
 "suresmile-clear-aligners": "6982397522a67279467e28ff_Screenshot_2026-02-03_130614.jpg",
}

# Service pages: slug -> data
SERVICES = {
 "cosmetic-dentistry": {
 "name": "Cosmetic Dentistry",
 "short": "Smile makeovers that combine veneers, whitening, bonding, and aligners, shaped around your face and goals.",
 "intro": "Cosmetic dentistry improves the appearance of your teeth, gums, and overall smile. From a single chipped tooth to a full smile makeover, our team designs treatment plans that look natural and last.",
 "what_it_is": "Cosmetic dentistry includes any treatment that improves how your smile looks, porcelain veneers, professional whitening, composite bonding, gum recontouring, tooth-coloured crowns, and clear-aligner orthodontics. We focus on conservative options first and only recommend more involved treatments when they will give a meaningfully better result.",
  "sub_services": [
  "Porcelain Veneers",
  "Dental Crowns",
  "Crown Lengthening",
  "White Spot Treatment",
  "Composite Bonding",
  "Smile Makeovers",
 ],
 "good_for": [
 "Discoloured or stained teeth",
 "Chipped, cracked, or worn enamel",
 "Small gaps or crowding",
 "Gummy smiles or uneven gum lines",
 "Old metal fillings or crowns showing through",
 ],
 "process": [
 ("Smile consultation", "We listen to what you want to change about your smile and discuss realistic, durable options."),
 ("Smile design", "Using photos and digital previews, we plan the size, shape, shade, and proportions of each tooth so the final result fits your face."),
 ("Treatment", "Depending on the plan, this can include whitening, bonding, <a href='/services/cosmetic-dentistry/'>veneers</a>, crowns, or clear aligners."),
 ("Final reveal & care", "We refine your bite, polish everything, and review home-care tips so your new smile lasts."),
 ],
 "faqs": [
 ("How do I know which treatment is right for me?", "Book a smile consultation. We will examine your teeth, listen to your goals, and explain conservative options before any major work."),
 ("Are veneers permanent?", "Porcelain <a href='/services/cosmetic-dentistry/'>veneers</a> require minimal enamel removal and last 10â15 years on average. They are considered a long-term commitment."),
 ("Will cosmetic dentistry damage my teeth?", "When planned and placed properly, modern <a href='/services/cosmetic-dentistry/'>cosmetic dentistry</a> preserves natural tooth structure and often strengthens weakened teeth."),
 ("Does insurance cover cosmetic work?", "Most insurance plans cover restorative components but not purely cosmetic treatments. We offer flexible payment plans and <a href='/payment-plans/'>Beautifi financing</a>."),
 ],
 },
 "dental-implants": {
 "name": "Dental Implants",
 "short": "Permanent, natural-looking tooth replacement using titanium implants and custom crowns.",
 "intro": "Dental implants replace missing teeth at the root level. Once integrated with your jawbone, the implant supports a custom crown that looks, feels, and functions like a natural tooth.",
 "what_it_is": "A dental implant is a small biocompatible titanium post that's surgically placed in the jawbone. Over a few months it fuses with the bone (osseointegration), then we attach a custom crown, or, for multiple missing teeth, an implant-supported bridge or denture.",
  "sub_services": [
  "Single Tooth Implants",
  "Multiple Implants",
  "Implant-Supported Bridges",
  "Full-Arch Implants",
  "Bone Grafting",
  "Implant Restoration",
 ],
 "good_for": [
 "Replacing one or more missing teeth",
 "Patients tired of removable dentures",
 "Preventing bone loss in the jaw after extraction",
 "Preserving adjacent teeth (no need to grind them down for a bridge)",
 ],
 "process": [
 ("Consultation & 3D scan", "We assess your bone, gums, and bite to confirm you're a candidate."),
 ("Implant placement", "The titanium post is placed in the jawbone under local anesthetic, with sedation if you prefer."),
 ("Healing & integration", "The implant fuses with the bone over 3–6 months."),
 ("Crown placement", "A custom crown is attached, blending perfectly with your natural teeth."),
 ],
 "faqs": [
 ("How long do dental implants last?", "With proper care, dental implants commonly last 20+ years and often a lifetime. The titanium post fuses with your jawbone and is one of the most durable restorations in dentistry. Routine <a href='/services/preventative-dentistry/'>hygiene cleanings</a> and a nightly home-care routine are what keep them healthy long term."),
 ("Is implant surgery painful?", "The procedure is done under local anesthetic, with the option of <a href='/services/nitrous-sedation/'>nitrous oxide sedation</a> if you're anxious. Most patients describe recovery as easier than a routine <a href='/services/oral-surgery/'>tooth extraction</a>, with mild soreness for two to four days that responds well to over-the-counter pain relievers."),
 ("Am I a candidate for dental implants?", "Most healthy adults with sufficient jawbone are candidates. If bone loss is a concern, bone grafting can rebuild the area before implant placement. <a href='/contact-us/'>Book a consultation</a> and we'll review your 3D scan and medical history before recommending a plan."),
 ("How much do dental implants cost in Hamilton?", "A single implant including the crown typically runs $4,000 to $6,000 in Ontario. Cost depends on the number of implants and whether grafting is needed. We provide a clear written estimate after your consultation and offer <a href='/payment-plans/'>Beautifi financing</a> with 0% options on qualifying treatments. <a href='/canadian-care-dental-plan/'>CDCP</a> does not typically cover implants, but private insurance plans often cover part of the crown."),
 ],
 },
 "endodontics": {
 "name": "Endodontics (Root Canals)",
 "short": "Gentle root canal therapy to save infected teeth and relieve severe tooth pain.",
 "intro": "Endodontics treats infection or inflammation inside a tooth's pulp. A root canal removes the damaged tissue, seals the canal, and saves the natural tooth, usually with no more discomfort than a routine filling.",
 "what_it_is": "Root canal therapy is performed when the nerve of a tooth becomes infected from deep decay, cracks, or trauma. Our team uses modern rotary instruments, magnification, and local anesthetic to clean and seal the canal in one to two visits.",
  "sub_services": [
  "Root Canal Therapy",
  "Endodontic Retreatment",
  "Pulp Capping",
  "Emergency Tooth Pain Relief",
 ],
 "good_for": [
 "Severe, lingering toothache",
 "Tooth sensitivity to heat or cold that does not go away",
 "Swelling, pus, or pimple-like bumps on the gum",
 "Deep cracks or large fractures with pulp exposure",
 ],
 "process": [
 ("Diagnosis", "We confirm the tooth needs treatment with an exam and X-ray."),
 ("Anesthetic & access", "The area is fully numbed; a small opening is made in the tooth."),
 ("Cleaning & shaping", "The infected pulp is removed and the canals are cleaned and disinfected."),
 ("Seal & restore", "The canal is sealed and the tooth is typically protected with a crown."),
 ],
 "faqs": [
 ("Does a root canal hurt?", "Modern <a href='/services/endodontics/'>root canal</a> aren't painful, most patients feel relief because the infection causing the pain is being treated."),
 ("Can I avoid extraction?", "Yes. A <a href='/services/endodontics/'>root canal</a> saves your natural tooth, which is almost always preferable to extraction."),
 ("Will I need a crown after?", "Back teeth almost always need a crown afterwards to prevent fracture. Front teeth sometimes don't."),
 ("How many visits will it take?", "Most <a href='/services/endodontics/'>root canal</a> are completed in one or two visits."),
 ],
 },
 "miscellaneous": {
 "name": "Additional Dental Services",
 "short": "Zoom in-office and take-home teeth whitening, sleep-apnea appliances, mouthguards, night guards, and TMJ care.",
 "intro": "Beyond our core services, we offer a range of supportive treatments. This page covers our whitening options (Zoom in-office and custom take-home trays), sleep-apnea appliances, athletic mouthguards, night guards for grinding, TMJ care, and oral cancer screening.",
 "what_it_is": "<strong>Zoom in-office whitening</strong> can lift your shade by 4 to 8 shades in a single 90-minute appointment. A professional-strength gel is activated by a special light over three or four short cycles. Perfect before a wedding, photoshoot, or any big event.<br /><br /><strong>Custom take-home whitening trays</strong> use lower-concentration gel and let you whiten gradually at home over 1 to 2 weeks. You keep the trays for life, top up with new gel any time. Many patients use Zoom for the initial result and take-home trays for touch-ups.<br /><br /><strong>Sleep-apnea appliances</strong> are custom oral appliances that hold the lower jaw slightly forward during sleep to keep the airway open. They are an alternative to CPAP for many patients with mild to moderate obstructive sleep apnea or chronic snoring, and a backup for CPAP intolerance.<br /><br />We also make <strong>custom athletic mouthguards</strong>, <strong>night guards</strong> for bruxism, and treat <strong>TMJ</strong> concerns with bite assessments and conservative therapy.",
  "sub_services": [
  "Zoom In-Office Whitening",
  "Take-Home Whitening Trays",
  "Sleep Apnea Appliances",
  "Anti-Snoring Appliances",
  "Athletic Mouthguards",
  "Night Guards (Bruxism)",
  "TMJ Care",
  "Oral Cancer Screening",
 ],
 "good_for": [
 "Patients who want a dramatic same-day whitening result (Zoom) or gradual home whitening (custom trays)",
 "Snorers and patients with mild to moderate sleep apnea who can't tolerate or don't want CPAP",
 "Athletes who play contact or fast-paced sports",
 "Patients who grind or clench at night, or wake with jaw pain or headaches",
 "Anyone with TMJ symptoms (jaw clicking, pain, limited opening)",
 "Routine oral cancer screening (included with every checkup)",
 ],
 "process": [
 ("Discussion of concerns", "We listen to what's going on and ask the right questions."),
 ("Targeted examination", "Clinical exam, plus digital scans, X-rays, or impressions if useful."),
 ("Whitening or appliance fit", "<a href='/services/miscellaneous/'>Zoom in-office whitening</a> is one 90-minute appointment. Take-home trays, mouthguards, night guards, and sleep-apnea appliances are typically made over two visits from a quick digital scan."),
 ("Follow-up and adjustment", "We check the fit and adjust as needed at no extra charge for the first month."),
 ],
 "faqs": [
 ("How much whiter will my teeth get with Zoom in-office whitening?", "Most patients see 4 to 8 shades of improvement after one Zoom session."),
 ("Zoom or take-home whitening, which is better?", "Zoom is faster and more dramatic. Take-home trays are gradual and easier to control sensitivity. Many patients combine both."),
 ("Will whitening damage my teeth?", "When done under dental supervision, professional whitening is safe and doesn't damage enamel. Mild temporary sensitivity is the most common side effect."),
 ("Can a dental appliance really help with sleep apnea?", "For many patients with mild to moderate obstructive <a href='/services/miscellaneous/'>sleep apnea appliances</a> or chronic snoring, yes. We work with your sleep physician on diagnosis and follow-up."),
 ("How long does a custom night guard last?", "A well-made <a href='/services/miscellaneous/'>night guard</a> typically lasts 3 to 5 years. We adjust the fit as needed."),
 ("Are mouthguards really necessary for sports?", "Yes, for any contact or fast-paced sport. A custom mouthguard fits far better than a boil-and-bite version and protects against concussion as well as broken teeth."),
 ("What can I do about jaw pain?", "We assess your bite, jaw joint, and habits, and start with conservative options like a <a href='/services/miscellaneous/'>night guard</a>, posture changes, and physiotherapy."),
 ("Do you do oral cancer screenings?", "Yes, every checkup includes one at no extra charge."),
 ],
 },
 "nitrous-sedation": {
 "name": "Nitrous Oxide (Laughing Gas) Sedation",
 "short": "A safe, gentle sedation option that helps anxious patients feel calm and comfortable during dental visits.",
 "intro": "Nitrous oxide sedation, also called laughing gas, helps you relax during dental treatment while remaining fully awake and responsive. It's one of the safest, most well-studied forms of sedation in dentistry.",
 "what_it_is": "You inhale a controlled mix of nitrous oxide and oxygen through a small comfortable nose mask. Within minutes you feel calm and relaxed. When the mask comes off, the effect wears off quickly, and you can drive yourself home.",
  "sub_services": [
  "Nitrous Oxide for Adults",
  "Nitrous Oxide for Children",
  "Sedation for Dental Anxiety",
  "Sedation for Longer Procedures",
 ],
 "good_for": [
 "Patients with dental anxiety or fear",
 "Children who need a little help getting through treatment",
 "Patients with a strong gag reflex",
 "Longer or more involved procedures (implants, surgery, root canals)",
 ],
 "process": [
 ("Pre-visit chat", "We talk through what to expect and confirm nitrous is right for you."),
 ("Mask & settling in", "A soft nose mask delivers the gas; within minutes you feel relaxed."),
 ("Treatment", "Your dentist proceeds with the planned treatment while you stay calm and aware."),
 ("Recovery", "After we switch you to pure oxygen for a few minutes, the effects wear off and you can leave on your own."),
 ],
 "faqs": [
 ("Is nitrous oxide safe?", "Yes, it's one of the safest sedatives in dentistry, used routinely for both adults and children."),
 ("Will I be unconscious?", "No. You remain fully awake and responsive, just more relaxed."),
 ("Can I drive home after?", "Yes. The effects wear off within minutes of removing the mask."),
 ("Is it covered by insurance?", "Many plans cover <a href='/services/nitrous-sedation/'>nitrous sedation</a>. We can verify before your appointment."),
 ],
 },
 "oral-surgery": {
 "name": "Oral Surgery & Wisdom Teeth Removal",
 "short": "Safe, precise extractions, wisdom-teeth removal, and minor oral surgery, all in-office.",
 "intro": "We perform most routine oral surgery in our office, including wisdom-teeth removal, complex extractions, biopsies, and pre-prosthetic surgery to prepare for dentures or implants.",
 "what_it_is": "Oral surgery covers any surgical procedure performed in or around the mouth. The most common are wisdom-tooth removal and extractions of severely damaged teeth. We use local anesthetic and offer nitrous oxide sedation to keep you comfortable.",
  "sub_services": [
  "Wisdom Teeth Removal",
  "Tooth Extractions",
  "Surgical Extractions",
  "Pre-Prosthetic Surgery",
  "Biopsies",
  "Cyst Removal",
 ],
 "good_for": [
 "Impacted, painful, or poorly-positioned wisdom teeth",
 "Teeth that can't be saved with a root canal or crown",
 "Preparing for dentures, implants, or orthodontics",
 "Removing cysts or suspicious tissue",
 ],
 "process": [
 ("Consultation & imaging", "A clinical exam and X-ray (or 3D scan) confirms the plan."),
 ("Comfort prep", "Local anesthetic and optional nitrous keep you comfortable."),
 ("Surgery", "The procedure is performed precisely and gently, typically in 30–60 minutes."),
 ("Aftercare", "Detailed home-care instructions, follow-up, and our phone line if you have questions."),
 ],
 "faqs": [
 ("Is wisdom tooth removal painful?", "Not during the procedure, local anesthetic numbs the area completely and <a href='/services/nitrous-sedation/'>nitrous oxide sedation</a> is available if you're anxious. Mild soreness for a few days afterwards is normal and responds well to over-the-counter pain relievers."),
 ("How long is recovery after oral surgery?", "Most patients return to normal activities within 2 to 4 days; full healing takes 1 to 2 weeks. We give you written aftercare instructions and a phone line you can use if anything seems off during recovery."),
 ("Will I need stitches?", "Sometimes. If used, the stitches typically dissolve on their own within a week, so there is no separate visit just for removal."),
 ("Can I drive home after wisdom teeth removal?", "Yes, if only local anesthetic or <a href='/services/nitrous-sedation/'>nitrous sedation</a> is used, you can drive yourself home. If you have IV sedation, you will need a ride."),
 ("How much does wisdom teeth removal cost in Hamilton?", "Cost depends on the number of teeth and whether they are erupted or impacted. We provide a clear written estimate after your consultation. Most private insurance plans cover oral surgery; <a href='/canadian-care-dental-plan/'>CDCP</a> also covers extractions for eligible patients. <a href='/payment-plans/'>Beautifi financing</a> is available for any out-of-pocket portion."),
 ],
 },
 "preventative-dentistry": {
 "name": "Preventative Dentistry & Dental Hygiene",
 "short": "Exams, professional cleanings, hygiene, sealants, fluoride, and X-rays that stop dental problems before they start.",
 "intro": "Preventive care is the most effective, and most affordable, kind of dentistry. Regular checkups, professional cleanings with our registered dental hygienists, and personalized home-care coaching catch small issues before they become big ones, saving you time, pain, and money.",
 "what_it_is": "Preventative dentistry at our office includes the full range of preventive and hygiene visits: thorough scaling and polishing by a registered dental hygienist, dental exams, digital X-rays, fluoride treatments, pit and fissure sealants for children, periodontal (gum) charting, oral cancer screenings, and personalized home-care advice. Most patients see us every six months; some need 3- to 4-month intervals based on gum health.",
  "sub_services": [
  "Dental Hygiene & Cleanings",
  "Oral Health & Hygiene Maintenance",
  "Dental Exams & Checkups",
  "Digital X-Rays",
  "Fluoride Treatments",
  "Pit & Fissure Sealants",
  "Diet Counselling",
  "Periodontal Charting",
  "Oral Cancer Screening",
 ],
 "good_for": [
 "Every patient, every age, but especially children and seniors",
 "Routine 6-month dental hygiene cleanings and checkups",
 "Patients with early gum disease (gingivitis) or established periodontal concerns",
 "Patients with crowns, bridges, implants, or aligners that need closer monitoring",
 "Anyone who wants to keep their natural teeth for life",
 ],
 "process": [
 ("Health review", "Your hygienist reviews your medical history and oral-care habits."),
 ("Thorough exam", "Your dentist checks your teeth, gums, bite, joints, and soft tissues."),
 ("X-rays as needed", "Modern digital X-rays use very low radiation and reveal hidden issues."),
 ("Hygiene and cleaning", "Scaling removes tartar buildup, polishing makes teeth feel smooth, and fluoride or sealants protect against future decay."),
 ("Tailored advice", "We discuss what's working well at home, where to focus, and book your next recall."),
 ],
 "faqs": [
 ("How often should I have a dental cleaning?", "Most patients see a hygienist every six months. Patients with gum disease usually need 3- to 4-month intervals to keep it under control."),
 ("Does scaling hurt?", "Modern ultrasonic and hand scaling is gentle. We can numb sensitive spots if needed."),
 ("Why do my gums bleed when I brush?", "Bleeding gums usually mean gingivitis (early gum disease). A professional cleaning plus better home care typically resolves it within a few weeks."),
 ("Are sealants worth it for kids?", "Yes. Sealants prevent the most common type of childhood cavity, the ones on chewing surfaces of molars."),
 ("Do I really need X-rays?", "We only take X-rays when they'll provide useful information. Most adults need a routine set every 1 to 2 years."),
 ("Are cleanings covered by insurance?", "Almost always. Most Canadian plans cover preventive visits, and <a href='/canadian-care-dental-plan/'>CDCP</a> covers preventive care for eligible patients."),
 ],
 },
 "restorative-dentistry": {
 "name": "Restorative Dentistry",
 "short": "Composite (white) fillings, crowns, and bridges that restore strength, function, and appearance.",
 "intro": "Restorative dentistry brings damaged teeth back to full health, strength, and natural appearance. We use tooth-coloured composite fillings for cavities, custom crowns to protect weakened teeth, and bridges to replace missing teeth, all with conservative techniques and modern materials.",
 "what_it_is": "Restorative dentistry includes three main treatments at our office. <strong>Composite (white) fillings</strong> repair cavities and small chips with a tooth-coloured resin that bonds to the tooth and blends with your natural enamel. <strong>Crowns</strong> are custom caps that fully cover a tooth weakened by decay, a fracture, or a root canal. <strong>Bridges</strong> use crowns on the teeth next to a gap to support a replacement tooth in between. We also offer inlays and onlays for medium-sized cavities and implant-supported crowns or bridges for missing teeth.",
  "sub_services": [
  "Composite (White) Fillings",
  "Dental Crowns",
  "Dental Bridges",
  "Inlays & Onlays",
  "Implant-Supported Crowns",
  "Replacing Silver Fillings",
 ],
 "good_for": [
 "Cavities small to large, including replacing old silver amalgam fillings with tooth-coloured composite",
 "Cracked, chipped, or worn teeth from grinding",
 "Teeth weakened by large fillings or a root canal (often need a crown)",
 "Replacing one or more missing teeth with a fixed bridge",
 "Improving the shape, size, or shade of a single tooth",
 ],
 "process": [
 ("Diagnosis and X-rays", "A clinical exam plus digital X-rays show the extent of decay or damage."),
 ("Conservative plan", "We recommend the simplest, most conservative option that will give a durable result: a filling when possible, an inlay/onlay if a filling won't hold, and a crown for larger damage."),
 ("Treatment", "Composite fillings finish in one visit. Crowns and bridges typically need two visits with a temporary in between, made from a digital scan (no goopy impressions)."),
 ("Bite check and follow-up", "We refine your bite, polish the restoration, and review home care before you leave."),
 ],
 "faqs": [
 ("Do you do composite (white) fillings?", "Yes. We use tooth-coloured composite for every new filling and routinely replace old silver amalgam fillings on request."),
 ("How long do composite fillings last?", "With good oral hygiene and regular checkups, <a href='/services/restorative-dentistry/'>composite fillings</a> typically last 7 to 10 years or longer."),
 ("How long do crowns and bridges last?", "Modern porcelain <a href='/services/restorative-dentistry/'>crowns and bridges</a> typically last 10 to 15 years or longer with proper care."),
 ("What is the difference between an inlay, onlay, and crown?", "An inlay sits inside the cusps of a tooth, an onlay covers one or more cusps, and a crown covers the entire tooth. We pick the option that preserves the most healthy tooth structure."),
 ("Will the restoration match my tooth?", "Yes. We shade-match every <a href='/services/restorative-dentistry/'>composite fillings</a>, inlay, onlay, and crown to your natural enamel so the restoration is virtually invisible."),
 ("Is restorative dentistry covered by insurance?", "Most Canadian plans cover restorative work. <a href='/canadian-care-dental-plan/'>CDCP</a> also covers basic restorations for eligible patients. We provide a written estimate before any major treatment."),
 ],
 },
 "suresmile-clear-aligners": {
 "name": "SureSmile Clear Aligners",
 "short": "Custom clear-aligner orthodontics that move teeth comfortably and discreetly.",
 "intro": "SureSmile is a clear-aligner system that uses precision-printed aligners to straighten teeth, comfortably, discreetly, and on a clear timeline. It's a great alternative to traditional braces for many adults and teens.",
 "what_it_is": "SureSmile combines digital scanning, 3D treatment planning, and a series of clear aligners worn 20–22 hours a day. Each set moves your teeth a small amount; you progress through the series until your smile is in the planned position.",
  "sub_services": [
  "SureSmile Clear Aligners",
  "Invisalign-Compatible Cases",
  "Bite Refinement",
  "Retainers & Retention",
 ],
 "good_for": [
 "Mild to moderate crowding or spacing",
 "Adults who want a discreet option",
 "Teens with all permanent teeth in place",
 "Patients refining a bite after previous orthodontics",
 ],
 "process": [
 ("Consultation & scan", "A 3D scan replaces traditional impressions, fast and comfortable."),
 ("Digital preview", "You see how your smile will move from start to finish before treatment begins."),
 ("Aligner series", "You wear each set for 1–2 weeks; check-in visits keep things on track."),
 ("Retention", "Custom retainers protect your new smile for the long term."),
 ],
 "faqs": [
 ("How is SureSmile different from Invisalign?", "Both are excellent clear-aligner systems with similar results. We carry both because each fits different cases best, and we will recommend honestly which one suits your bite, timeline, and budget. Curious about <a href='/services/cosmetic-dentistry/'>cosmetic dentistry</a> add-ons to refine your smile after alignment? We can discuss that at your consultation."),
 ("Will SureSmile clear aligners affect my speech?", "Most patients adjust within a few days. A slight lisp on s and th sounds is common at first and fades quickly as your tongue gets used to the trays."),
 ("Can I drink coffee with my aligners?", "Aligners should be removed for anything other than water to avoid staining and damage. Take them out for coffee, tea, juice, and meals, then brush before putting them back in."),
 ("How much do SureSmile clear aligners cost in Hamilton?", "Cost varies by case complexity. We provide a clear estimate up-front and offer <a href='/payment-plans/'>Beautifi financing</a>, including 0% options on qualifying plans. Most private insurance plans cover part of orthodontic treatment; <a href='/canadian-care-dental-plan/'>CDCP</a> generally does not cover orthodontics."),
 ("Are clear aligners a good option for adults?", "Yes. The majority of our clear-aligner patients are adults. They are virtually invisible while you wear them, easy to remove for special occasions, and most cases finish in 6 to 18 months. <a href='/contact-us/'>Book a consultation</a> and we will scan your bite, show you a digital preview of the final result, and explain timing."),
 ],
 },
}

# Team members: slug -> data
# Doctors (canonical at /team/, with /about/ canonical-redirecting to /team/)
TEAM = {
 "dr-fadi-dawood": {
 "name": "Dr. Fadi Dawood",
 "role": "Owner",
 "photo": "695fc139ba075a99589a81cc_Owner.png",
 "bio": [
 "Dr. Fadi Dawood is the owner of Hamilton Care Dental Centre. He founded the practice in 2012 with a simple goal: deliver thorough, gentle dentistry that treats every patient like family.",
 "Patients consistently describe Dr. Dawood as patient, thorough, and genuinely caring. He focuses on family dentistry, dental implants, and complex restorative cases.",
 ],
 },
 "dr-bassam-petros": {
 "name": "Dr. Bassam Petros",
 "role": "Dentist",
 "photo": "695fc16d95d4cc3dcb72b1e8_Associate_Dentist.png",
 "bio": [
 "Dr. Bassam Petros is an associate dentist at Hamilton Care Dental Centre. He treats patients of all ages and is particularly known for his gentle chairside manner with children and anxious patients.",
 "Dr. Petros provides thorough care including preventive dentistry, cosmetic treatments, restorative work, and clear-aligner orthodontics.",
 ],
 },
 "dr-peter-markho": {
 "name": "Dr. Peter Markho",
 "role": "Associate Dentist",
 "photo": "petermarkho.png",
 "bio": [
 "Dr. Peter Markho is an associate dentist at Hamilton Care Dental Centre. He provides general and cosmetic dental services for patients across Hamilton.",
 "Dr. Markho is committed to ongoing education and to using current, evidence-based techniques to deliver clear, conservative care.",
 ],
 },
 "maha": {
 "name": "Maha",
 "role": "Dental Assistant",
 "photo": "69544ac938513c9b12f2de96_Maha.JPEG",
 "bio": [
 "Maha is a dental assistant at Hamilton Care Dental Centre. She works closely with our dentists during procedures and is known for her calm, reassuring presence.",
 "Maha is often one of the first faces patients see in the operatory, and one of the reasons so many of our reviews mention how comfortable they felt during treatment.",
 ],
 },
 "makayla": {
 "name": "Makayla",
 "role": "Dental Assistant",
 "photo": "69544ac938513c9b12f2de81_Makayla.JPEG",
 "bio": [
 "Makayla is a dental assistant who supports the team during a wide range of procedures, from routine cleanings to implant surgery.",
 "She is friendly, organized, and dedicated to making every patient feel at ease.",
 ],
 },
 "viktoriya": {
 "name": "Viktoriya",
 "role": "Dental Assistant",
 "photo": "69544ac938513c9b12f2de97_Vikoriya.JPEG",
 "bio": [
 "Viktoriya is a dental assistant at Hamilton Care Dental Centre. She helps coordinate appointments, prepares treatment rooms, and assists chairside during procedures.",
 "Her attention to detail and warm communication help make every visit smooth.",
 ],
 },
 # /team/ only members
 "darcy": {
 "name": "Darcy",
 "role": "Registered Dental Hygienist",
 "photo": "695fc64490e9e79261cb959f_Darcy.png",
 "bio": [
 "Darcy is a registered dental hygienist at Hamilton Care Dental Centre. She provides thorough, gentle cleanings, periodontal care, and personalized home-care coaching.",
 "Many of our long-term patients see Darcy every six months, and she is a big reason they keep coming back.",
 ],
 },
 "erazel": {
 "name": "Erazel",
 "role": "Dental Assistant",
 "photo": "erazel.png",
 "bio": [
 "Erazel is a dental assistant at Hamilton Care Dental Centre. She works chairside with our dentists across general, cosmetic, and surgical procedures.",
 "Patients often mention how comfortable she helps them feel, especially during longer appointments. Her calm, attentive style sets the tone for a smooth visit.",
 ],
 },
 "fatima": {
 "name": "Fatima",
 "role": "Dental Receptionist",
 "photo": "695fc3d46c849965cb0aeba0_Fatima.png",
 "bio": [
 "Fatima is a dental receptionist at Hamilton Care Dental Centre. She welcomes patients, books appointments, and handles insurance questions and CDCP claims so every visit starts smoothly.",
 "She is fluent at navigating Canadian dental insurance and the Canadian Dental Care Plan, and works hard to make care as affordable and predictable as possible.",
 ],
 },
 "lucy": {
 "name": "Lucy",
 "role": "Assistant Office Manager",
 "photo": "695fc36600851c5991192f35_Lucy.jpg",
 "bio": [
 "Lucy is our Assistant Office Manager. She supports the day-to-day running of the practice, helps coordinate the schedule, and keeps things moving for our front-office and clinical teams.",
 "Her warm welcome is often the first thing patients mention in our reviews.",
 ],
 },
 "maheen": {
 "name": "Maheen",
 "role": "Registered Dental Hygienist",
 "photo": "695fc4f744be23b3ad24c69d_Maheen.png",
 "bio": [
 "Maheen is a Registered Dental Hygienist at Hamilton Care Dental Centre. She delivers gentle, thorough cleanings and personalized home-care coaching for patients of every age.",
 "She is known for her calm chairside manner and her attention to detail with periodontal care.",
 ],
 },
 "melissa": {
 "name": "Melissa",
 "role": "Registered Dental Hygienist",
 "photo": "695fc52d311f8540d54a3aba_Melissa.png",
 "bio": [
 "Melissa is a Registered Dental Hygienist focused on gentle preventive care and patient education.",
 "She shapes home-care routines to each patient's needs, including those wearing braces, clear aligners, or implants.",
 ],
 },
 "nahrin": {
 "name": "Nahrin",
 "role": "Dental Receptionist",
 "photo": "695fc3a74c192fae4f9469aa_Nahrin.jpg",
 "bio": [
 "Nahrin is a dental receptionist at Hamilton Care Dental Centre. She handles bookings, follow-up calls, and insurance questions so patients always know what to expect before their visit.",
 "Her organized, friendly style keeps the schedule running on time.",
 ],
 },
 "paeez": {
 "name": "Paeez",
 "role": "Dental Assistant",
 "photo": "695fc40212b44ca167596e2b_Paeez.png",
 "bio": [
 "Paeez is a dental assistant at Hamilton Care Dental Centre. He works chairside with our dentists across general and surgical procedures and helps every appointment run smoothly.",
 "Patients appreciate his calm, helpful approach and his attention to comfort during longer treatments.",
 ],
 },
 "saif": {
 "name": "Saif",
 "role": "Denturist",
 "photo": "695fc28fb77fe3cc807785ae_Saif.jpg",
 "bio": [
 "Saif is the denturist at Hamilton Care Dental Centre. He designs and fits complete and partial dentures, immediate dentures, and implant-retained dentures right in our office.",
 "Working on-site means faster turnaround, better aesthetics, and tight coordination with our dental team for extractions, implants, and follow-up adjustments.",
 ],
 },
 "sally": {
 "name": "Sally",
 "role": "Registered Restorative Dental Hygienist & Office Manager",
 "photo": "695fc30246bc7e1590459662_Sally.png",
 "bio": [
 "Sally is our Office Manager and a Registered Restorative Dental Hygienist. She splits her time between leading the office team and providing thorough hygiene visits and restorative care for patients.",
 "Her cheerful, organized approach sets the tone for the whole practice.",
 ],
 },
 "sana": {
 "name": "Sana",
 "role": "Dental Assistant",
 "photo": "695fc471b77fe3cc80788b19_Sana.png",
 "bio": [
 "Sana is a dental assistant at Hamilton Care Dental Centre. She supports our dentists chairside across general, cosmetic, and surgical procedures.",
 "Patients appreciate her gentle approach and the way she keeps them informed throughout each step.",
 ],
 },
 "torees": {
 "name": "Torees",
 "role": "Registered Dental Hygienist",
 "photo": "695fc4a2e6fcbb9f696acf41_Torees.jpg",
 "bio": [
 "Torees is a Registered Dental Hygienist at Hamilton Care Dental Centre. She delivers gentle cleanings and periodontal care, with a focus on long-term gum health.",
 "She is known for keeping patients informed and comfortable throughout every appointment.",
 ],
 },
}


# Blog posts: slug -> data. Original copy.
# Date format: ISO 8601
BLOG = {
 "canadian-dental-care-plan-cdcp----how-hamilton-care-dental-supports-it": {
 "title": "Canadian Dental Care Plan (CDCP): How Hamilton Care Dental Supports It",
 "seo_title": "CDCP in Hamilton: How We Support Patients",
 "date": "2026-02-20",
 "hero": "69544ac938513c9b12f2dded_Dentists-Denturistour-story-1024x1024.png",
 "summary": "The Canadian Dental Care Plan helps eligible Canadians afford dental care. Here's what it covers, who qualifies, and how Hamilton Care Dental supports CDCP patients.",
 "keywords": "CDCP Hamilton, Canadian Dental Care Plan, dental insurance Hamilton, affordable dentist Hamilton",
 "body": [
 ("What is the CDCP?", "The <a href='/canadian-care-dental-plan/'>Canadian Dental Care Plan</a> (<a href='/canadian-care-dental-plan/'>CDCP</a>) is a federal program that helps eligible Canadians cover the cost of dental care. It's administered through Sun Life and covers a wide range of routine and restorative treatments. Hamilton Care Dental Centre is proud to accept <a href='/canadian-care-dental-plan/'>CDCP</a> for all eligible patients."),
 ("Who qualifies?", "<a href='/canadian-care-dental-plan/'>CDCP</a> is available to Canadian residents without private dental insurance whose adjusted family net income is below the program threshold. Eligibility expanded in 2025 to include most adults under 65 in addition to seniors and children. You can confirm your eligibility on the Government of Canada <a href='/canadian-care-dental-plan/'>CDCP</a> page."),
 ("What does CDCP cover?", "Covered services include exams, cleanings, X-rays, fillings, extractions, <a href='/services/miscellaneous/'>dentures</a>, <a href='/services/endodontics/'>root canal</a>, and many restorative treatments. Some treatments may require pre-authorization. We'll explain exactly what's covered before any treatment begins so there are no surprises."),
 ("How we make CDCP simple", "We submit all claims directly to Sun Life on your behalf. There is no paperwork for you to fill out, and your co-pay (if any) is collected at the appointment. If you have questions about coverage, our treatment coordinators can walk you through it before you book."),
 ("Booking a CDCP appointment", "Call us at (289) 755-2568 or <a href='/contact-us/'>book online</a>. Have your <a href='/canadian-care-dental-plan/'>CDCP</a> member ID number handy and we will take care of the rest."),
 ],
 },
 "dental-benefits-in-2026-use-your-insurance-early-beautifi-0-financing-for-a-more-confident-smile-in-hamilton": {
 "title": "Dental Benefits in 2026: Use Your Insurance Early + Beautifi 0% Financing in Hamilton",
 "seo_title": "Use 2026 Dental Benefits Early + Beautifi 0% Financing",
 "date": "2026-04-22",
 "hero": "6a04c1d25217f5426cd9cbe6_beautify_financing.webp",
 "summary": "Most Canadian dental plans reset annually. Here's how to use your 2026 benefits early, and how Beautifi 0% financing covers what insurance doesn't.",
 "keywords": "dental insurance 2026, Beautifi financing Hamilton, dental payment plans, affordable dentistry Hamilton",
 "body": [
 ("Your dental benefits reset every year", "Most Canadian private dental plans reset their annual maximum on January 1. Any unused benefits from the previous year are gone, they don't roll over. The patients who get the most value from their plan are the ones who book early in the year."),
 ("Why booking in Q1 is smart", "Early in the year, your full annual maximum is available. If you need restorative work, splitting it across two calendar years can let you use the maximum twice, once in December, again in January, covering a larger portion of treatment."),
 ("What if treatment costs more than my insurance covers?", "We offer <a href='/payment-plans/'>Beautifi financing</a>, flexible monthly payment plans, including 0% options on qualifying treatments. There's no penalty for early repayment, and applications take just a few minutes."),
 ("Combining insurance + financing", "Patients regularly use insurance to cover the diagnostic and restorative portion of treatment, then use Beautifi for cosmetic or elective parts (whitening, <a href='/services/cosmetic-dentistry/'>veneers</a>, Invisalign). Together, you get the smile you want with predictable monthly payments."),
 ("Get a clear estimate first", "Before any major treatment, we provide a written estimate showing what insurance is likely to pay and what your out-of-pocket cost would be. <a href='tel:+12897552568'>Call (289) 755-2568</a> or <a href='/contact-us/'>book online</a> to start the conversation."),
 ],
 },
 "dentist-near-me-on-hamilton-mountain-your-local-dental-clinic-on-upper-ottawa": {
 "title": "Dentist Near Me on Hamilton Mountain: Your Local Dental Clinic on Upper Ottawa",
 "seo_title": "Dentist Near Me on Hamilton Mountain (Upper Ottawa)",
 "date": "2026-05-13",
 "hero": "69dd355bbbc53f8d5f980cf0_hamilton-care-denta-centre-new-patients.jpg",
 "summary": "Looking for a trusted dentist on Hamilton Mountain? Here's why families across Upper Ottawa, Stoney Creek, and Ancaster choose Hamilton Care Dental Centre.",
 "keywords": "dentist near me Hamilton Mountain, Hamilton dentist, Upper Ottawa dentist, family dentist Hamilton",
 "body": [
 ("Right in the heart of Hamilton Mountain", "Hamilton Care Dental Centre sits on Upper Ottawa Street, easy to reach from Mountain neighbourhoods, Stoney Creek, Ancaster, and Dundas. We have free parking right at the unit and plenty of natural light inside."),
 ("Thorough care under one roof", "From routine cleanings and check-ups to <a href='/services/dental-implants/'>dental implants</a>, Invisalign, <a href='/services/oral-surgery/'>oral surgery</a>, and emergency care, almost everything you need is provided in-office. That means fewer referrals out and less time off work for you."),
 ("Family-friendly, all-ages care", "We see toddlers having their first checkup, teens in Invisalign, busy parents getting cleanings, and seniors restoring their smiles. Patients love that the whole family can be seen in one office."),
 ("Same-day and emergency appointments", "If you're in pain, call us first. We hold time every day for emergencies, broken teeth, severe pain, lost fillings, swelling, and aim to see you the same day."),
 ("Booking and contact", "<a href='tel:+12897552568'>Call (289) 755-2568</a>, email office@hamiltoncaredental.ca, or <a href='/contact-us/'>book online</a>. We're open Monday–Friday 8–6 and Saturday 9–3."),
 ],
 },
 "emergency-dentist-near-me-in-hamilton-same-day-care": {
 "title": "Emergency Dentist Near Me in Hamilton: Same-Day Care When You Need It",
 "seo_title": "Emergency Dentist in Hamilton: Same-Day Care",
 "date": "2026-05-09",
 "hero": "69dd3551d20cffd06b71bc71_emergency-dental-hamilton-care-dental-centre.jpg",
 "summary": "Severe tooth pain, a broken tooth, swelling, or a lost filling? Here's what to do, and how Hamilton Care Dental Centre handles dental emergencies.",
 "keywords": "emergency dentist Hamilton, same-day dental Hamilton, tooth pain Hamilton, broken tooth Hamilton",
 "body": [
 ("What counts as a dental emergency?", "Severe tooth pain, swelling, a knocked-out tooth, a broken tooth with sharp edges, a lost filling or crown that's exposing nerve, and uncontrolled bleeding all qualify as dental emergencies. Don't wait, call us right away."),
 ("First-aid steps before you arrive", "Rinse with warm salt water for pain and infection. Apply cold compress to the outside of the cheek for swelling. For a knocked-out tooth, gently rinse it (don't scrub), and store it in milk or your own saliva until you get to us."),
 ("How we handle emergencies", "<a href='tel:+12897552568'>Call (289) 755-2568</a>, even after hours, our message will tell you the best way to reach us. During business hours we hold appointment slots for emergencies and aim to see you the same day."),
 ("Common emergency treatments", "We provide pain relief, drainage of infections, temporary crowns, emergency <a href='/services/endodontics/'>root canal</a>, extractions, and stabilization of broken teeth. For most emergencies you can be comfortable within an hour or two of arriving."),
 ("Cost and insurance for emergencies", "Most dental insurance plans cover emergency exams and treatment. <a href='/canadian-care-dental-plan/'>CDCP</a> also covers emergency care for eligible patients. We provide a clear cost estimate before treatment."),
 ],
 },
 "how-much-does-dental-care-cost-in-hamilton-what-patients-should-expect-in-2025": {
 "title": "How Much Does Dental Care Cost in Hamilton? What to Expect in 2025",
 "seo_title": "Dental Care Costs in Hamilton: 2025 Patient Guide",
 "date": "2026-04-08",
 "hero": "69544ac938513c9b12f2dde4_Untitled-design-17-min-555x740.png",
 "summary": "A clear, honest look at dental costs in Hamilton, checkups, fillings, crowns, implants, Invisalign, and how insurance, CDCP, and financing help.",
 "keywords": "dental costs Hamilton, dentist prices Hamilton, dental fee guide 2025 Ontario, affordable dentist Hamilton",
 "body": [
 ("Where dental fees come from", "Most Ontario dentists base their fees on the Ontario Dental Association (ODA) fee guide. The guide is updated annually and lists a suggested fee for every dental code. Your fee may vary slightly depending on the complexity of your case."),
 ("Routine care", "A new-patient exam, cleaning, and X-rays typically falls in the $200–$350 range. Recall (6-month) exams plus a cleaning are usually $150–$250. <a href='/canadian-care-dental-plan/'>CDCP</a> and most private insurance cover these visits."),
 ("Restorations", "A composite (white) filling ranges from $150 to $350 depending on size and location. A porcelain crown is typically $1,200–$1,800. A <a href='/services/endodontics/'>root canal</a> ranges from $700 (front tooth) to $1,500 (molar), plus a crown afterwards for back teeth."),
 ("Implants and orthodontics", "A single <a href='/services/dental-implants/'>dental implants</a> including the crown typically runs $4,000–$6,000 in Ontario. Invisalign and <a href='/services/suresmile-clear-aligners/'>SureSmile clear aligners</a> range from $4,500 to $8,500 depending on case complexity."),
 ("How to make care affordable", "Insurance covers a large share of routine and restorative care. <a href='/canadian-care-dental-plan/'>CDCP</a> covers eligible patients for most basic services. For the rest, <a href='/payment-plans/'>Beautifi financing</a> offers flexible monthly plans. Ask for a written estimate before any major treatment, you should never be surprised by the bill."),
 ],
 },
 "how-often-should-you-visit-the-dentist-what-the-experts-recommend": {
 "title": "How Often Should You Visit the Dentist? What the Experts Recommend",
 "seo_title": "How Often Should You Visit the Dentist?",
 "date": "2026-01-08",
 "hero": "6956260aec543390f64c4164_istockphoto-2203896947-612x612-1.jpg",
 "summary": "Most people are told 'every six months', but is that right for you? Here's what the evidence and experts say about ideal dental visit frequency.",
 "keywords": "how often dentist visit, dental checkup frequency, preventive dentistry Hamilton",
 "body": [
 ("The standard recommendation", "The Canadian Dental Association recommends a checkup and professional cleaning every six months for most healthy adults. This catches small problems early, when they are easier and cheaper to fix, and keeps gum disease in check."),
 ("Why six months?", "Six months is short enough that most early cavities can be detected before they reach the nerve, and that tartar buildup can be removed before it causes gum disease. It's long enough that visits don't become a hassle for most patients."),
 ("When you might need more frequent visits", "Patients with active gum disease often need a cleaning every 3–4 months. Patients with crowns, bridges, implants, or aligners benefit from closer monitoring. So do patients who grind their teeth or who have a history of frequent cavities."),
 ("When less-frequent visits might be reasonable", "Some patients with excellent home care, no gum disease, and very low caries risk may safely extend to 9 or 12 months. We will tell you honestly if you fit that category."),
 ("How to know what's right for you", "At your next visit, ask your dentist directly: 'What recall interval is right for me?' We will give you a real answer based on your gums, your habits, and your history, not a one-size-fits-all schedule."),
 ],
 },
 "preventive-dentistry-in-hamilton-how-regular-care-saves-you-time-pain-money": {
 "title": "Preventive Dentistry in Hamilton: How Regular Care Saves You Time, Pain, and Money",
 "seo_title": "Preventive Dentistry in Hamilton: Save Time and Money",
 "date": "2026-02-06",
 "hero": "69544ac938513c9b12f2dded_Dentists-Denturistour-story-1024x1024.png",
 "summary": "Skipping dental visits to save money is one of the most expensive choices you can make. Here's how preventive care pays off, financially and in quality of life.",
 "keywords": "preventive dentistry Hamilton, dental cleanings Hamilton, dental exam Hamilton, oral health prevention",
 "body": [
 ("The cost of skipping care", "A routine cleaning costs roughly $150. A filling on the same tooth a year later, after a cavity has formed, costs $200–$350. If the cavity reaches the nerve and needs a <a href='/services/endodontics/'>root canal</a> plus crown, you're looking at $2,500+. The math heavily favours prevention."),
 ("What preventive dentistry actually does", "Regular cleanings remove tartar that you can't remove at home, which is the root cause of most gum disease. Routine exams catch cavities, cracks, oral cancers, and worn teeth before they need expensive treatment."),
 ("Beyond the teeth", "Gum disease is linked to cardiovascular disease, diabetes complications, and adverse pregnancy outcomes. Keeping your gums healthy supports the rest of your body, too."),
 ("Home care that multiplies the value of your visits", "Brush twice a day with fluoride toothpaste. Floss or use interdental brushes daily. Limit sticky sweets between meals. Drink water through the day. None of this is fancy, but consistently doing it dramatically reduces dental problems."),
 ("Booking your preventive visit", "If it's been more than a year, book now. <a href='tel:+12897552568'>Call (289) 755-2568</a> or schedule online. <a href='/canadian-care-dental-plan/'>CDCP</a> and most insurance cover preventive care fully."),
 ],
 },
 "the-technology-behind-your-smile-how-modern-dentistry-is-changing-the-game": {
 "title": "The Technology Behind Your Smile: How Modern Dentistry Is Changing the Game",
 "seo_title": "The Technology Behind Your Smile",
 "date": "2026-03-10",
 "hero": "69823a60259f0beff7e0e59d_IMG_1932.JPG",
 "summary": "Digital X-rays, intraoral scanners, 3D printing, clear aligners, modern dentistry looks nothing like it did 20 years ago. Here's what's actually new.",
 "keywords": "modern dental technology, digital dentistry Hamilton, intraoral scanner Hamilton, 3D dental printing",
 "body": [
 ("Digital X-rays", "Digital sensors capture images instantly with up to 90% less radiation than traditional film. The images appear on a screen the moment they are taken, so we can review them with you chairside."),
 ("Intraoral scanners", "Goopy impression trays are largely a thing of the past. A small wand scans your teeth in seconds, building a precise 3D model that goes straight to the lab, faster results, more accurate restorations, and a more comfortable experience."),
 ("3D treatment planning", "For implants, orthodontics, and complex restorations, we plan the entire treatment digitally before touching a tooth. You see a preview of the final result, and the surgery or aligner sequence is optimized for predictability."),
 ("Clear aligners", "Clear aligners like Invisalign and <a href='/services/suresmile-clear-aligners/'>SureSmile clear aligners</a> use 3D scanning and high-precision printing to move teeth in a controlled sequence, discreet, comfortable, and removable."),
 ("Why this matters for patients", "Faster appointments, less discomfort, better-fitting restorations, and clearer communication. Technology in dentistry isn't about gadgets, it's about better outcomes for patients."),
 ],
 },
 "why-families-in-hamilton-choose-hamilton-care-dental-centre": {
 "title": "Why Families in Hamilton Choose Hamilton Care Dental Centre",
 "seo_title": "Why Hamilton Families Choose Hamilton Care Dental",
 "date": "2026-05-05",
 "hero": "69544ac938513c9b12f2ddec_IMG_7577-Edited-min-1024x683.jpg",
 "summary": "From toddlers to grandparents, we treat the whole family under one roof. Here's what families consistently tell us they appreciate.",
 "keywords": "family dentist Hamilton, best dentist Hamilton families, Hamilton family dental clinic",
 "body": [
 ("One office for the whole family", "Parents save time by booking kids and adults together. We coordinate appointments so the whole family can be seen in one visit, and we have streaming on the ceiling in some rooms to keep little ones distracted."),
 ("Patient, gentle care for kids", "Kids' first dental visits set the tone for life. Our team takes the time to build trust, counting teeth, showing tools, and never rushing. We don't push treatment that can wait."),
 ("Senior-friendly", "Many seniors come to us for <a href='/services/miscellaneous/'>dentures</a>, implants, and complex restorative work. Direct billing and <a href='/canadian-care-dental-plan/'>CDCP</a> support make care accessible."),
 ("Family logistics, sorted", "Direct insurance billing, evening and Saturday hours, free parking, plenty of natural light, and an office that doesn't feel sterile. Small things that add up to a better experience."),
 ("A 4.9-star average from 89+ reviews", "Patients consistently mention three things in their reviews: gentle care, honest recommendations, and a friendly team. That's the practice we set out to build."),
 ],
 },
 "wisdom-teeth-removal-near-me-in-hamilton-expert-oral-surgery-on-hamilton-mountain": {
 "title": "Wisdom Teeth Removal in Hamilton: Expert Oral Surgery on Hamilton Mountain",
 "seo_title": "Wisdom Teeth Removal in Hamilton: Oral Surgery",
 "date": "2026-01-22",
 "hero": "69dd357ddd5316a68625f91e_wisdom-teeth-removal-hamilton-care-dental-centre.jpg",
 "summary": "Most adults need wisdom teeth out at some point. Here's how to know when, what the procedure is like, and how recovery actually goes.",
 "keywords": "wisdom teeth removal Hamilton, oral surgery Hamilton Mountain, wisdom tooth extraction Hamilton",
 "body": [
 ("When wisdom teeth need to come out", "Most patients need wisdom teeth removed between ages 17 and 25, before the roots are fully formed. Common reasons: impaction (the tooth can't fully erupt), crowding adjacent teeth, infection or cysts, or repeated gum inflammation."),
 ("Sedation options", "We perform wisdom tooth removal under local anesthetic, with nitrous oxide (laughing gas) sedation for added comfort. For more complex cases, IV sedation is available with our anesthetist."),
 ("What recovery looks like", "Mild swelling and soreness for 2–4 days. Most patients return to school or office work within 3 days. Avoid hard, crunchy, or sticky foods for the first week and don't smoke during healing."),
 ("Cost and insurance", "Wisdom-tooth removal is covered by most Canadian dental plans, including <a href='/canadian-care-dental-plan/'>CDCP</a>. We provide a written estimate before surgery. <a href='/payment-plans/'>Beautifi financing</a> is available for any out-of-pocket costs."),
 ("Booking a consultation", "We start with a panoramic X-ray or 3D scan to see the position of the teeth. From there we explain your options. <a href='tel:+12897552568'>Call (289) 755-2568</a> to book a consultation."),
 ],
 },
 "your-smile-your-confidence-the-rise-of-cosmetic-dentistry-in-hamilton": {
 "title": "Your Smile, Your Confidence: The Rise of Cosmetic Dentistry in Hamilton",
 "seo_title": "Cosmetic Dentistry in Hamilton: Confident Smiles",
 "date": "2026-03-24",
 "hero": "69575bb957af7f49684deea5_Screenshot-2025-04-14-112747.png",
 "summary": "Cosmetic dentistry has gone mainstream, and it's not just about veneers. Here's what's possible, what's realistic, and how to choose what's right for you.",
 "keywords": "cosmetic dentistry Hamilton, smile makeover Hamilton, veneers Hamilton, teeth whitening Hamilton",
 "body": [
 ("Why cosmetic dentistry is booming", "Smartphone cameras, video calls, and social media have made everyone more aware of their smile. At the same time, modern materials, <a href='/services/cosmetic-dentistry/'>veneers</a>, durable composite, predictable whitening, have made beautiful, natural-looking results more accessible than ever."),
 ("Conservative first", "We always recommend the least invasive option that will achieve your goal. For many patients, that's professional whitening plus a few hours of composite bonding, not full <a href='/services/cosmetic-dentistry/'>veneers</a>."),
 ("Common cosmetic treatments", "Professional whitening (Zoom or take-home), composite bonding for chips and gaps, <a href='/services/cosmetic-dentistry/'>veneers</a> for major changes in shape and shade, Invisalign or <a href='/services/suresmile-clear-aligners/'>SureSmile clear aligners</a> for alignment, gum recontouring for gummy smiles, and tooth-coloured crowns to replace old metal restorations."),
 ("How long results last", "Whitening lasts 1–3 years. Composite bonding lasts 5–10 years and can be touched up. Porcelain <a href='/services/cosmetic-dentistry/'>veneers</a> last 10–15 years on average."),
 ("Booking a smile consultation", "Cosmetic consultations are relaxed, we listen to your goals, take photos, and explain real options with real costs. <a href='tel:+12897552568'>Call (289) 755-2568</a> or <a href='/contact-us/'>book online</a>."),
 ],
 },
}
